### ISSUE TITLE
Could not queue multiple volleys even with enough channels

### ISSUE THREAD

**Issue by rmorrise** [stackcollision/Nebulous-BugReporting#103]
**Describe the bug**
I'm not sure if this is a bug, but I'm not able to set up missile volleys against multiple targets, even when I have enough programming channels. It feels like I should be able to.

**To Reproduce**
1. Set up a fleet of frigates with 3 channels each.
2. Set WCON HOLD
3. Shift-click, fire a 2-missile salvo on one target. Confirm. Shift-click, fire a 1-missile salvo on another target. Confirm.
4. Set to WCON FREE

**Expected behavior**
Each ship should fire 2 missiles at target A, then 1 missile at target B.

**Actual behavior**
Only the 1-missile salvo is fired.

**Additional context**

**Attachments**
Screenshot of missile design:
https://discord.com/channels/409638848302153728/425835550193483784/1004443417419460670

**Comment by rmorrise** [comment]
Link to fleet files:
https://discord.com/channels/409638848302153728/425835550193483784/1004447785673826365

**Comment by stackcollision** [comment]
With the MPC changes, missile launchers now behave similarly to other weapons.  Issuing a new target order will cancel other active orders for those launchers.
