### ISSUE TITLE
Strange RPF behavior at point blank

### ISSUE THREAD

**Issue by Snowblind111** [stackcollision/Nebulous-BugReporting#106]
**Describe the bug**
120mm RPF fired at missiles while said missiles are extremely close to the firing guns will inexplicably change direction of travel when passing by the missiles.

**To Reproduce**
1. Build a 120mm RPF PD setup, preferably with a high ROF.
2. Launch enough missiles at it that at least some get to close range
3. Any shots fired at extremely close range will path erroneously

**Expected behavior**
RPF should either pass the missiles without interacting with them if within fusing distance, or detonate if outside that.

**Additional context**
My impression from watching this behavior several times is that the RPF direction of travel changes whenever it would detonate on a missile but fails to do so due to insufficient flight time for its fuse to arm.

**Attachments**
![image](https://user-images.githubusercontent.com/108890191/182833865-7335c213-4042-4709-b075-121d4d722811.png)

**Comment by NicholasZonenberg** [comment]
I have also seen this happen.  I have not been able to grab a screenshot before the shell trail faded.

Seems to just happen at random somewhat rarely.  No idea what might exactly trigger it.  

An additional observation is this behavior also looks like what can happen with really large warhead AMM.  Such as a S3 AMM with 200m blast radius detonating when the incoming missile was at the edge of that 200m.  But a missile trail was drawn from where the AMM detonated to the destroyed missile.
