### ISSUE TITLE
Defensive Missiles not tartgeting Size 1 Offensive missiles

### ISSUE THREAD

**Issue by thebluehaloguy** [stackcollision/Nebulous-BugReporting#11]
**Describe the bug**
I have a valid Defensive missile that will launch and attack normal missiles. When I made a Frigate with size 1 Offensive missiles, the Defensive missiles did not engage those missiles.

**To Reproduce**
1. Launch a game with a ship with defensive missiles and another ship with the Size 1 Offensive Missiles
2. Wait for AI to shoot you, or shoot the AI Defensive ship 
3. Watch as the Defensive missiles fail to engage the enemy size 1 missiles.

**Expected behavior**
It was expected that the defensive missiles would launch to intercept the size 1 offensive missiles

**Additional context**
CaptainWolf was able to download my files and replicate this issue. He then used his own missiles which are size 2, and the defensive missiles did work, so the issue seems to be with that of size 1 offense.
**Attachments**
It says it isnt supporting the file type for the specific ships I use, if you need the files just let me know.

**Comment by stackcollision** [comment]
Added defensive targeting doctrine to missiles.  Default Riposte template still will not target size 1 missiles automatically, but the player can change it.
