### ISSUE TITLE
Missile Warhead Display Numbers are Incorrect

### ISSUE THREAD

**Issue by RocketPuppy** [stackcollision/Nebulous-BugReporting#110]
The warhead display numbers when selecting the warhead are incorrect for all missiles except the tempest. There appears to be some scaling factor applied to the different missiles.

**To Reproduce**
1. Pick a non-tempest missile
2. Pick a warhead and make it size 1
3. Observe the point breakdown displays a different number than it shows in the selection box.

**Expected behavior**

**Additional context**
This also applies to the damage numbers and other stats.

**Attachments**
![20220806214506_1](https://user-images.githubusercontent.com/1556657/183271542-acee7c95-764f-4967-b3d7-13bbd104a214.jpg)

**Comment by stackcollision** [comment]
This is due to missile socket size scaling.
