### ISSUE TITLE
Turning Spotlight on causes SAR S2s to fly in random directions.

### ISSUE THREAD

**Issue by RocketPuppy** [stackcollision/Nebulous-BugReporting#116]
**Describe the bug**
I turned on an illuminator, and my S2 SARH missiles that were flying in a straight line, without being activated, spread out in random directions taking the radar cones out of range of the targets.

**Comment by stackcollision** [comment]
Cannot reproduce.  Please provide a video, save file, or replication steps.  Odds are the enemy started jamming your missiles around the same time you activated your spotlight, which causes the random directions.
