### ISSUE TITLE
Hybrids staging early under jamming with SARH and active radar seekers

### ISSUE THREAD

**Issue by gaishu-isshoku** [stackcollision/Nebulous-BugReporting#128]
**Describe the bug**
When under the effect of jamming, hybrid missiles fitted with SARH or active radar seekers will instantly stage.

**To Reproduce**
Launch a hybrid with either seeker equipped as primary, activate jamming in its direction, watch it stage.

**Expected behavior**
The missile to continue without staging, as the jamming should prevent detection of a target, rather than providing a false target on which to trigger staging.

**Attachments**
Video of behavior: https://streamable.com/dl40v2

**Comment by thebluehaloguy** [comment]
HEY, I just wanted to add that in a salvo of 5, 2 of the missiles sprinted early, but 3 of them behaved normally. So there seems to be some inconsistency in the missiles. Mazer lmk in discord if you need that video.
