### ISSUE TITLE
EO validators seem to be letting missiles lock onto chaff and decoys. 

### ISSUE THREAD

**Issue by ZachoWacko** [stackcollision/Nebulous-BugReporting#133]
**Describe the bug**
Extended range radar seekers with an EO validator seem to not work effectively anymore.

**To Reproduce**
Launch an S3H ERAR with EO validation missile at a target with chaff and decoys. 
The missile will go after decoys until EO range but then won't change to the ship as it should. 

**Expected behavior**
The missile should at 3km pick the ships out and stage using the EO validation. 

**Attachments**
[HC 3.5k.fleet.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/9354539/HC.3.5k.fleet.zip)
Is the ship with the missiles, any target fleet with chaff or decoys will work.

**Comment by Cebasiz** [comment]
[Bad validation behavior seeker view.webm](https://user-images.githubusercontent.com/10738550/184992533-9601013e-1930-4f5d-a95f-46b199e12448.webm)
[Bad validation behavior.webm](https://user-images.githubusercontent.com/10738550/184992561-14955ccf-3266-45e8-ac25-4500981d5eab.webm)

videos showing behavior hope it helps

**Comment by Cebasiz** [comment]
[aaaaaa2.webm](https://user-images.githubusercontent.com/10738550/185010437-fe62230c-084f-4605-8402-ed6f82a25621.webm)
[aaaaaa.webm](https://user-images.githubusercontent.com/10738550/185010443-5888c8fd-06d3-47a2-b05a-b7411f94e5cc.webm)
[S3H misses.webm](https://user-images.githubusercontent.com/10738550/185010445-5725b7fa-4c3f-4b22-8479-3ae72ee6d1be.webm)

more examples posted in missiles testing channels also.

**Comment by Cebasiz** [comment]
[validation being ignored.webm](https://user-images.githubusercontent.com/10738550/185214367-c95206b6-7ccf-4a46-b263-d889e8c1b2b9.webm)

example video
