### ISSUE TITLE
Red error text during skirmish and disconnect during skirmish (separate matches).

### ISSUE THREAD

**Issue by treesniper12** [stackcollision/Nebulous-BugReporting#152]
**Describe the bug**
Red text appeared for all clients (did not seem to appear for the host) during a skirmish match on pillars. The match afterward on Nyx's Eye had a mass disconnect after a few reactor blooms caught some clippers. Both are contained in the attached log.

**Attachments**
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/10151328/Player.log)

**Comment by Tempestfox3** [comment]
[Crash_Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/10151354/Crash_Player.log)

player log attached as well, was present in both matches first match gave red text error but did not Disconnect, second match red text error log and did disconnect.
