### ISSUE TITLE
MLS launchers infinite ammo

### ISSUE THREAD

**Issue by LaffyChan** [stackcollision/Nebulous-BugReporting#157]
Both MLS-2 and MLS-3 expend no missiles when launching, giving them infinite ammo. Always happens. Regular vls seem to be unaffected.

1. Enter skirmish with a mls launcher
2. Launch a few missiles from it
3. Watch the missile reserves
4. Keep firing till bored I guess????

**Expected behavior**
Missiles run out

**Additional context**
Not just a visual bug, missiles are actually infinite

![image](https://user-images.githubusercontent.com/119881855/205697644-1bfbb860-cbdf-4e39-87ff-4560b4df681a.png)

**Comment by cannonfodder1** [comment]
I can also confirm this behaviour, infinite torpedoes
![20221205121739_1](https://user-images.githubusercontent.com/1369684/205735375-4c2a93e2-3284-4aff-b4db-654790c3a2c8.jpg)
