### ISSUE TITLE
Double Reinforced Structure Modules do not raise Component DR past 50%

### ISSUE THREAD

**Issue by Apocal43** [stackcollision/Nebulous-BugReporting#158]
**Describe the bug**
Taking two Reinforced Structure modules will correctly lower crew vulnerability but will not raise Component DR past 50% on an Ocello Command Cruiser

**To Reproduce**
1. Go to Fleet Editor.
2. Add an Ocello.
3. Scroll down to module section and add two Reinforced Structure modules.
4. Observe that Crew Vulnerability is correctly lowered for both but Component DR stops at 50%, in spite of the green bonus text increasing from 25% to 48.04%.

**Expected behavior**
A note in the module text to indicate that Component DR is capped at 50% and either:
1) The green bonus text for CompDR to stop at 25%
2) CompDR increased past 50%

**Additional context**
Multiple reinforced structure modules work correctly on Lineships.

**Attachments**
Pic included.
![reinforced structure compDR](https://user-images.githubusercontent.com/43554459/205732921-8b352a5d-0603-4d8e-8a91-2f176a277bee.png)

**Comment by LaffyChan** [comment]
This was intended, check https://discord.com/channels/409638848302153728/992853592664973352/1039753768444624968
(— 09/11/2022 changelog)
