### ISSUE TITLE
Active Seekers do not trigger sprint stage outside of ~1500m for SGM-H-300 when fired on track

### ISSUE THREAD

**Issue by yannisvetster** [stackcollision/Nebulous-BugReporting#16]
**Describe the bug**
When utilizing an active seeker such as the Steerable Extended Active Radar Seeker with the SGM-H-300 body, the missile does not trigger its sprint stage at nearly the seeker's maximum range despite the sprint stage having a range exceeding 4km. The sprint stage only triggers approximately when the enemy's ship shows up via visual.

**To Reproduce**
1. Using supplied fleet file
2. Load into a singleplayer game using the fleet
3. Launch SGM-H-345 Shipwreck at enemy target via track and **NOT** POS
4. Observe that sprint stage does not trigger until nearly point blank when the missile is configured to have a 4823m sprint range.
**Expected behavior**
The missile sprint stage begins at 3858m away from the target according to the shared info that sprint stage occurs at 80% of the sprint range.

**Additional context**

**Attachments**
[MISSILE TEST GAMING.txt](https://github.com/stackcollision/Nebulous-BugReporting/files/9034199/MISSILE.TEST.GAMING.txt)
[Video of the reported behavior occurring](https://streamable.com/rgwh4g)

**Comment by yannisvetster** [comment]
Testing with a regular Steerable Active Radar Seeker, Fixed Active Radar Seeker, and the Electro-Optical and also observed that it did not separate at the maximum range of the seekers (2000, 2000, 2500) but rather at the range when the battleship pops up to visual as well which is around ~1500m.

Testing with the Command Guided seeker has it start its sprint stage when the target was within the sprint stage's maximum range and has the behavior working as intended.

**Comment by yannisvetster** [comment]
[Small demonstration video of what the expected behavior should look like](https://streamable.com/2yfbxo)

**Comment by yannisvetster** [comment]
Testing further, the issue has been narrowed down to when firing via track (Right clicking a track and deploying missiles)

Deploying the missile via waypoint will have it deploy the sprint at expected distance from a valid target

**Comment by TexanByTrade** [comment]
I should say here that I tried to duplicate and it works fine for me for some reason.
