### ISSUE TITLE
Reinforced Structure does not improve Component DR on Clippers.

### ISSUE THREAD

**Issue by Apocal43** [stackcollision/Nebulous-BugReporting#160]
**Describe the bug**
Adding a Reinforced Structure module to a Clipper correctly reduces crew vulnerability but does not increase Component DR, in spite of the green bonus text.

**To Reproduce**
1. Fleet Editor.
2. Add a Clipper and Reinforced Structure module.
3. Observe that Component DR does not increase.

**Expected behavior**
Either no bonus percentage displayed or an increase in Component DR.

**Additional context**
If intended, this should be noted somewhere and perhaps warning text added as guard rails.

**Attachments**
Attach any screenshots, logs, fleet files, etc that may help.
![component DR at 0](https://user-images.githubusercontent.com/43554459/205786268-14346d2d-4448-4dc8-ad58-5f06d54f312f.jpg)

**Comment by xlwoon** [comment]
I believe it might be intended, as "+25%" of zero is still +zero
Probably good if it got some explanation text, or a warning when using the part ("hull base DR 0%!! this part will provide no benefit")

To note: what might also be a little confusing is that DR is a % "unit" value, so it might be unclear if the support module is increasing the base stat by an absolute 25% value (0% + 25% == 25%) or by a factor of 25% (0% * 125% == 0%)
