### ISSUE TITLE
Missiles leaving MLS launchers on Bulk Freighters do not clear ship

### ISSUE THREAD

**Issue by titowulk** [stackcollision/Nebulous-BugReporting#174]
**Describe the bug**
When using one of the longer Bulk Freighter configurations, MLS on the direct opposite side of the target will hit the rear and front of the launching ship instead of remaining clear until proper clearance is achieved.

**To Reproduce**
1. Outfit Bulk Freighter (Long configuration) with MLS racks
2. Face 90 degrees from the target ship
3. Order missiles fired
4. Missiles will impact the engine block and front of the launching ship

**Expected behavior**
The missiles should ideally be launched clear of the ship and given enough room to maneuver around the lengthier bulk freighter layouts. As it stands, the only time this isn't an issue is if you intentionally repeatedly generate a ship to get a shorter configuration where the missiles can clear. 

**Attachments**
https://youtu.be/yHjg-cwDec8

**Comment by captainwolfer** [comment]
Also had this happen when firing MLS-3s towards targets to one side, as visible in this screenshot
![20221217190341_1](https://user-images.githubusercontent.com/108598089/208279341-0ced225a-10a3-4321-93a6-550b2820eb9f.jpg)
