### ISSUE TITLE
T20 100mm turret on tug's bottom mount intermittently hits ownship when firing at target in front of the ship

### ISSUE THREAD

**Issue by Cebasiz** [stackcollision/Nebulous-BugReporting#183]
**Describe the bug**
T20 turret hits ownship when firing at forward target.

**To Reproduce**
Put T20 turret on tug
fire at forward target
"commander we're taking fire here" 
note: may hit  grabby arms but even when target is direct front it still hits the lip of the front of the hull. 

**Expected behavior**
this not happen

**Comment by a-nop** [comment]
Same for jammers on tug top mount, while spinal is aiming the top mount can't jam the same target.
