### ISSUE TITLE
Sundrive and prowler speed buff and debuff dont cancel out to 0.

### ISSUE THREAD

**Issue by 13lacklight** [stackcollision/Nebulous-BugReporting#192]
**Describe the bug**
Sundrive and prowler speed buff and debuff dont cancel out to 0 despite being a 25% + and 25% down.

**To Reproduce**
Add a sundrive and Prowler to an ocello.

**Expected behavior**
Should read 0 speed change, but there is none.

**Comment by stackcollision** [comment]
Not a bug, all modifiers are sorted and then diminishing returns are applied.
