### ISSUE TITLE
Game ending too early due to false 'combat incapability' judgement

### ISSUE THREAD

**Issue by DesertSaker** [stackcollision/Nebulous-BugReporting#2]
**Describe the bug**
The game initiates a game-ending countdown timer in annihilation, despite active combat capability remaining on ships on both teams. 

**To Reproduce**
1. Engage in an annihilation game
2. Take damage to some MLS tubes, perhaps getting one destroyed
3. Countdown initiates, despite having a functional MLS, CIC, offensive missiles remaining, thrusters 

**Expected behavior**
The timer should not start until all missiles are expended, or all magazines and MLS are destroyed.

**Additional context**
This was a 1v1 game on Cliff, Annihilation

**Attachments**
Screenshots depict me firing missiles after the countdown remaining, with missiles remaining in the magazine.

![Nebulous Screenshot 2022 07 02 - 21 39 22 83](https://user-images.githubusercontent.com/108598484/177021298-36c05f2f-9595-4fe8-a666-db5b51fa2f7e.png)
![Nebulous Screenshot 2022 07 02 - 21 39 30 94](https://user-images.githubusercontent.com/108598484/177021301-c239f08a-c931-4c73-8be0-d7928f579f8f.png)
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/9033944/Player.log)

**Comment by stackcollision** [comment]
This was due to the MLS having its "offensive" flag not set correctly.
