### ISSUE TITLE
Defensive Container Missiles redtext and go to menu

### ISSUE THREAD

**Issue by RocketPuppy** [stackcollision/Nebulous-BugReporting#215]
**Describe the bug**
Bring a container ship with HE-FRAG containers set to defensive. When they launch, there is redtext and the game ends. When I try to start another skirmish, there are no players (me or a cpu) in the lobby.

**To Reproduce**
1. Start skirmish with attached fleet
2. Launch missiles to trigger the AMM containers to fire
3. redtext

**Expected behavior**
No redtext.

**Attachments**
Fleet file and log in the zip
[messin with containers.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/10367798/messin.with.containers.zip)

**Comment by prophetb1** [comment]
Tried testing container ships, I'll say that the containers just in general behave like this, not exclusive to AMM.
