### ISSUE TITLE
AMMs doing too much damage

### ISSUE THREAD

**Issue by captainwolfer** [stackcollision/Nebulous-BugReporting#229]
**Describe the bug**
An AMM with Blast Frag EL deals 40 component damage, but is killing in one hit S3H with 60 health

**To Reproduce**
1. Load provided fleet in testing range, against itself
2. Fire 1 S3H at frigate
3. Observe as the S3H is killed in one hit (assuming the hit roll succeeds)

**Expected behavior**
Since AMM should deal 40 damage, it should take two of them to kill a S3H

Attached Fleet and recording of bug
**Attachments**
https://user-images.githubusercontent.com/108598089/213849050-83d886e2-6fa7-4990-b5d6-808bfdf97c27.mp4
[1 AMM test.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/10471723/1.AMM.test.zip)

**Comment by captainwolfer** [comment]
Note: I did some more testing - The AMMs are dealing more than 87 damage (s3h with 2 hardened), but less than 110 damage (because I just tested it and 1 AMM can't kill a S3 torpedo)

**Comment by TexanByTrade** [comment]
Maybe I found why this is:

FragmentationWarheadDescriptor.DamageComponents uses

`parent.ApplyDamageReduction(this._componentDamage.GetValue((float)base._socketSize))`

instead of

`parent.ApplyDamageReduction(this.ComponentDamage)` which would use _weightedSocketSize.

The description in the fleet editor uses _weightedSocketSize.

**Comment by d0d0b1rd** [comment]
One thing to note: 
Pre-missile update ripostes dealt 50 damage, almost the exact same as 5/1 s1 AMMs now.
I think the damage of s1 AMMs are fine, and if the socket weight issue is fixed, the values should be adjusted such that s1 AMMs deal approximately the same damage as they did before.
