### ISSUE TITLE
New patch 1/24/2023 Null refs

### ISSUE THREAD

**Issue by ZachoWacko** [stackcollision/Nebulous-BugReporting#233]
Missiles had null refs and container banks were not working. Rockets would not fire. 
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/10486967/Player.log)

**Comment by vren55** [comment]
Player file host file attached
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/10486990/Player.log)
