### ISSUE TITLE
Rapid DC teams not using restores from the large DC storage

### ISSUE THREAD

**Issue by Nocek15** [stackcollision/Nebulous-BugReporting#238]
The rapid DC lockers can not use restores from the large DC storage

1. Build a ship without DC lockers other then rapid DC lockers and the large DC storages
2. Go into a skrimish with another or control AI 
3. Have the second person or the AI shoot the ship until a component gets destroyed/greyed out
4. Attempt to repair the destroyed component

The DC teams will repair the ship however they will not even begin to restore the component

![bug](https://user-images.githubusercontent.com/78977098/215832746-50fe1c0a-be3e-4967-b45a-e990d1fd1a2b.PNG)

**Comment by stackcollision** [comment]
Not a bug, rapid DC teams do not have restore capability.
