### ISSUE TITLE
DC teams can be reassigned from critical debuffs.

### ISSUE THREAD

**Issue by HardworkingSlacker** [stackcollision/Nebulous-BugReporting#245]
**Describe the bug**
You can manually reassign a dc team that is working on a critical debuff like reactor overloads.

**To Reproduce**
Take a ship and cause a critical debuff on it.
Open damage control panel and manually set priorities until all teams not working on a critical debuff are assigned to a specific repair duty.
Then assign another priority and you will see the team working on the critical debuff move away from it.

**Expected behavior**
The dc team(s) working on critical debuffs should not be reassignable thus not respond to priority changes since they work on the highest priority already.

**Additional context**
In the video:
The team that was NOT assigned to move away from the critical debuff finished repairs on a debuff and then started working on repairing the module itself.

**Attachments**
https://user-images.githubusercontent.com/90241675/216477526-a59843c3-6059-4510-8689-05f393a4c14d.mp4

**Comment by stackcollision** [comment]
This is not a bug, critical events have the second highest priority, with player-assigned priority having the highest.  If you want to prioritize repairs but not have your crews leave a critical event, prioritize that one as well.
