### ISSUE TITLE
CTD 4v4 Pillars during reactor bloom

### ISSUE THREAD

**Issue by WeebleKeneeble** [stackcollision/Nebulous-BugReporting#246]
**Describe the bug**
CTD as host of game, crash occurred when reactor overload happened and camera focus was on ship.

**To Reproduce**
1. play game
2. get crit
3. look at ship
4. profit

**Expected behavior**
game not crashing from looking at pretty graphics

**Additional context**
none

**Attachments**
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/10574878/Player.log)

**Comment by stackcollision** [comment]
No useful information in the log.  Do you have a crash dump in your logs folder?
