### ISSUE TITLE
redtext and crash to menu while loading into game, 4v4 pillars

### ISSUE THREAD

**Issue by Cebasiz** [stackcollision/Nebulous-BugReporting#247]
**Describe the bug**
4v4 pillars

[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/10575808/Player.log)

**Comment by prophetb1** [comment]
[Crashes.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/10575876/Crashes.zip)
crash logs after trying to exit game
renamed from .rar to .zip because github is nasty and doesn't like .log, .dmp files.
