### ISSUE TITLE
Point Defenses Failing to Engage Valid Targets

### ISSUE THREAD

**Issue by treesniper12** [stackcollision/Nebulous-BugReporting#253]
**Describe the bug**
In certain circumstances, point defenses (kinetic point defenses may be particularly affected?) will "give up" and experience dramatic reductions in response time or stop responding to threats entirely.  The result is that sometimes point defenses will not engage active threats, or only a few weapons will engage when more should be available.

**To Reproduce**
In a singleplayer skirmish, fire a high volume of missiles at a ship or group of ships, and observe that there is a point where point defenses stop engaging when there are still active threats.

**Expected behavior**
Point defenses should continue to engage targets to their ability regardless of time dilation, host slow down, or high-volume attacks.

**Additional context**
This "overloading" seems more common in multiplayer games when there is significant time dilation, but similar results can be observed in singleplayer testing when there is a large volume of missile fire. The issue is significantly worse in multiplayer games with multiple container ships active. PD weapons will frequently go blue in status and display 'target out of range' or 'target masked by hull' while this is happening, it is possible they are getting stuck assigned to bad targets by the PD controller.

**Attachments**

In this video, '1-GUNS' has a disabled Defender on its right side and two functional defenders on its left side, '2-GUNS' has two functional Defenders on the right side and one functional defender on its top left side, neither ship is missing radar panels and they are not under enemy jamming. Observe how the Defenders on '2-GUNS' fail to provide cover to '1-GUNS', and the Defenders on '1-GUNS' (selected for some of the clips.

https://user-images.githubusercontent.com/31147266/216801930-fca12986-efff-435a-9268-5f453a4c6c03.mp4

In this video a Defender fails to engage enemy missiles (much to the despair of Rymarq), its host ship is not under jamming and has active radars on the side of the missiles, the Defender seems to spin in confusion.

https://user-images.githubusercontent.com/31147266/216802161-a2e685d8-9b3b-46ca-94b0-c82660baaa68.mp4

(Youtube Video) PD stops engaging targets at the end of the salvo.

https://youtu.be/UL3EbRZ3MmQ

**Comment by RocketPuppy** [comment]
Here's a demo at 10% speed and 100% speed. You can see pretty clearly that the PD just kinda stops for almost two seconds of game time. https://www.youtube.com/watch?v=fL2HB_Wwh8I

Quoting my Discord message here for the record:
> Mazer, I've been looking into the PD controller because there's some behavior we're seeing in game where there are "gaps" in PD fire, usually seen at the tail end of a missile strike. It looks like the PD controller assigns targets either every two seconds, when a new track appears, or when a track disappears. I'm wondering if there could be an issue where the sensor update loop and the PD controller loop are synchronizing such that the PD controller tasks a turret to a missile, the missile is destroyed just after the top of the sensor update loop and the top of the PD controller loop, so the turret stays assigned to that track for a whole second until the track drops on the next sensor update. That seems like it could explain the behavior we've been seeing. I'll file a bug report with a video attached.

**Comment by cannonfodder1** [comment]
I've been running into this a lot, here's one from the other night where my Defenders just stopped firing once the missiles got within 500m or so (the only shots going out are from a Stonewall). Even after the initial torpedo hits, at least one of the Defenders on that side is still intact and should still be firing at the followup spikers.
https://youtu.be/_0ezHU0bAOw
