### ISSUE TITLE
Manually PD prioritizing a missile defeats decoy support module

### ISSUE THREAD

**Issue by Cebasiz** [stackcollision/Nebulous-BugReporting#263]
**Describe the bug**
Because of the way the game handles object tracking (probably) manually prioritizing a missile prioritizes it through all phases of flight regardless of sprint phase separation and decoys. This effectively means that long range decoy missile strikes don't work because the target will probably shift+z the missiles which can defeat hundreds of points in decoys and the only counterplay is to jam them down to such an extent they never see the missile, removing the point of putting decoys on the missile in the first place.

**To Reproduce**
1. Be a defending ship defending from decoy-enabled missiles.
2. Prioritize an incoming missile threat pre-separation
3. watch as your auroras nail the missile despite it's corkscrew/decoy/sprint approach since the "truth data" of the sim knows exactly which object is the prioritized missile. 

**Expected behavior**
Separation or decoy deployment should clear out manual PD prioritization at least once so that decoys have value against someone willing to put in the minimum amount of micro.

**Comment by HardworkingSlacker** [comment]
That doesn't sound like a bug.
If you put in the time to manually assign targets, your PD should follow your orders regardless of decoys.

**Comment by Cebasiz** [comment]
I'll try to keep this short and concise 

Question 1: What are we trying to model here exactly 

So, the current way the model works is like this:

The captain walks off to the space warfare officer's console and points at the red icons on the screen
"SWO Jones, make sure to hit those ones."
"Which ones, sir."
"Those ones. Right there. All of them."
"OK." 

The missiles then start a rapid corkscrew approach and the 6 missiles break into 24 separate contacts and very rapidly approach the ship. The radar and the radar operator pair inherently now know completely inerrantly which missiles are real vs. fake because ??? ??? If the radar capability and operator capability are such that SWO Jones can identify real contacts from fake contacts with zero error and engage them, then why require the micro? If he can't, then how does the player manually designating them make sense? If SWO Jones can engage the real targets with a zero error rate, then why do the decoys exist in the first place since everyone in the game world knows that the radar capability is such that decoys don't matter?

Question 2: Seriously, how do you tell which missile is real when the missile splits into four pieces? As I explain above it's game logic, but in-universe, how does manually designating things as PD priority make sense when decoys are being ejected? How in-world do people "know" which missile is the real missile? 

Question 2a: If you say "because the missile is maneuvering stupid" then why are decoys a thing if it's that easy for the radar to discriminate

Question 3: Why is it okay that very expensive penaids quite literally do nothing if people press one button. This is one of the reasons decoys is terrible. Probably the reason. If we want penaids to work then this probably has to go.
