### ISSUE TITLE
"phantom rock" bug

### ISSUE THREAD

**Issue by Cebasiz** [stackcollision/Nebulous-BugReporting#264]
**Describe the bug**
Sometimes ships get "stuck" in open space, where they are stuck against a "phantom rock" as if they're colliding with something that isn't there. They can't move like they're bumping up against terrain. 

**To Reproduce**
1. I've only seen this happen once, but it happened to several of us in a game.

**Expected behavior**
Ships do not get stuck on invisible terrain

**Additional context**
Happened to Beef & I's sprinters and CLs, but seems ship agnostic. Have never seen this before.

**Comment by Shamas-MacShamas** [comment]
I've done some small-scale testing of this in Skirmish vs AI, and at least on Pillars it appears to take the form of expanded hitboxes for the asteroids. The UI does not display a collision warning when attempting to enter these areas. The amount of expansion is not the same for all asteroids, with the large rock surrounding D and the large rock under A affected especially severely. I independently discovered the bug when testing a monitor fleet, so I wasn't able to check many places at the time.
