### ISSUE TITLE
Cell cookoff in container banks, instead of container bank cookoff

### ISSUE THREAD

**Issue by prophetb1** [stackcollision/Nebulous-BugReporting#266]
**Describe the bug**
Container banks can roll the cell cookoff crit, which is silly, considering they're not cells at all!

**To Reproduce**
1. Shoot container banks
2. Hope you get the cell cookoff
3. What do you mean cell cookoffs, we don't have cells?!

**Expected behavior**
The banks should get the far more spectacular and expected container bank cookoff.

**Additional context**
na

**Attachments**

Attach any screenshots, logs, fleet files, etc that may help.
![20230211202854_1](https://user-images.githubusercontent.com/110350899/218275232-da5c4b7a-0fe9-436e-8f09-b1031bf6e808.jpg)
![20230211202852_1](https://user-images.githubusercontent.com/110350899/218275236-2af37576-f362-412f-87b0-6d680c5f8e7a.jpg)

**Comment by stackcollision** [comment]
They are technically cell launchers, which is why they can get this event.
