### ISSUE TITLE
Turreted ewar equipment counts as weapon for purposes of determining who has capture zone priority and if a ship has no offensive ability

### ISSUE THREAD

**Issue by cannonfodder1** [stackcollision/Nebulous-BugReporting#269]
Long-standing bug that hasn’t been fixed yet and I thought should have a GitHub issue, turreted ewar counts as a weapon so if you have a gun corvette and a jammer frigate in a capture zone, they both count as armed. This is probably not how things are supposed to work, I remember Mazer saying it was incorrect behaviour in a voice channel a few weeks back. 

Personally have seen this happen with Blanket jammers, other players claim it also occurs with the EWR and LRT. Likely a bug common to all turreted ewar, jammers and directional radars and maybe even illuminators and fire control as well.

EDIT: other players have informed me that this bug also affects the no offensive ability checks, meaning if a team has no offensive weapons left but does have ewar, the game will not be ended. I am less sure if this part is an unintentional bug, it may be intentional to allow crippled teams a chance to win on points.

**To Reproduce**
1. Take ship containing no offensive weapons and only jammers, capture a control point.
2. Take ship on opposing team with any offensive weapon and move it into the same control point’s capture zone.
3. Observe that the armed ship cannot override the ewar ship, the control point is not being counter capped.

**Expected behavior**
Ships with offensive weapons should have capture priority over unarmed ships.

**Comment by RocketPuppy** [comment]
Also occurs with EWAR items like spotlights.
