### ISSUE TITLE
BSSJ fails to suppress enemy radar, radar PD

### ISSUE THREAD

**Issue by Cebasiz** [stackcollision/Nebulous-BugReporting#287]
**Describe the bug**
6 incoming BSSJs with target in FOV fail to suppress it's radar and PD. the target, a bridgemaster LN with no pinpoint, achieves track and P11 lock @ 3.5km~ and engages with all PD including P11, P60 up until point of impact. No other radars were nearby to help it achieve first detect, as all other radars besides it's own were off.

**To Reproduce**
1. Build hybrid missile with BSSJ
2. Fire 6 at target with no other radars to assist in tracking
3. Target achieves track and lock very early in the ingress of the hybrids despite being under heavy jamming

**Expected behavior**
BSSJ should suppress the target's radar and radar FCRs unless friendlies are around to help that are outside the jamming cone. 

**Additional context**
Repeated several times to make sure, I tested if it was the P60 somehow acquiring without a radar lock, and even with just P11 the target detects at ~3.5km with a bridgemaster and starts firing with no other ships present in the scenario to see the missiles with offboard.

Another very strange occurrence is that the missile turns on the jammer at initial detection at 5km. the jammer turns on shortly after, but the defending ship doesn't get a JAM indication until 3.5km. I have no idea if that's related but thought I'd include in case it helps diagnose.

^edit: the above may just be because jammer max range (4km) + lagtime between it getting into range and the receiving ship getting the jam notification in combo with high target speed 

**Attachments**

https://discord.com/channels/409638848302153728/812451950096154634/1076565099331989534

[Fleets.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/10774946/Fleets.zip)

**Comment by HardworkingSlacker** [comment]
Additional context:
https://www.youtube.com/watch?v=C9Ib6bUPvv4
