### ISSUE TITLE
You cannot target or shoot at friendly lifeboats

### ISSUE THREAD

**Issue by AhriiIsHot** [stackcollision/Nebulous-BugReporting#29]
**Describe the bug**
I cant shoot at allied lifeboats

**To Reproduce**
1. Load caltrops
2. Wait for ally to get missile dumped
3. Get bored
4. Try to shoot at the lifeboat
5. Cannot shoot at them

**Expected behavior**
Being able to lock and shoot at lifeboats

**Additional context**
Lemmie commit my war crimes

**Attachments**
![Screenshot (3819)](https://user-images.githubusercontent.com/78585334/177069355-6687b3e6-27dc-4728-bb2d-f5e791730817.png)

**Comment by treesniper12** [comment]
![bruh](https://user-images.githubusercontent.com/31147266/177073209-d44c3e47-9e4f-4ae8-bb74-be2fce49de6f.gif)

**Comment by thebluehaloguy** [comment]
Brug what
