### ISSUE TITLE
SARH Cruise Terminal Maneuvers

### ISSUE THREAD

**Issue by Avalonux** [stackcollision/Nebulous-BugReporting#309]
**Describe the bug**
S2 SARH Cruise with terminal maneuvers won't activate when guided to a target.

**To Reproduce**
Fire SARH with Cruise, POS or on a direct track.
Illuminate target.
Watch missiles go straight in
**Expected behavior**
Just like with SARH Direct guidance, they should have started their terminal maneuvers at 4k from the target, but they guided in like they didn't have any terminal maneuvers equipped. 

**Additional context**
Worked fine with other seeker combos, EO/HOJ, ACT/HOJ, etc

**Attachments**

**Comment by Cebasiz** [comment]
As an addendum, I think this might be happening on all passive seekers. it was reported a day or so ago that it happens with ARAD CRUISE as well.
