### ISSUE TITLE
Red text after firing Cyclone missiles

### ISSUE THREAD

**Issue by AhriiIsHot** [stackcollision/Nebulous-BugReporting#31]
**Describe the bug**
It says something I don't understand.

**To Reproduce**
Join game
Deploy
Fire Sabre missiles
Red text

**Expected behavior**
Not that

**Additional context**
N/A

**Attachments**
Attach any screenshots, logs, fleet files, etc that may help.

[missilebug.txt](https://github.com/stackcollision/Nebulous-BugReporting/files/9036496/missilebug.txt)
[1xbote3.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/9036542/1xbote3.zip)

**Comment by stackcollision** [comment]
There are no errors or exceptions in your log.  I cannot reproduce it with the provided fleet in singleplayer.  Does this only occur in multiplayer?
