### ISSUE TITLE
CM-4 container still shows 8 points cost for the EO seeker

### ISSUE THREAD

**Issue by AIRB0RNE84** [stackcollision/Nebulous-BugReporting#310]
**Describe the bug**
CM-4 container still shows 8 points cost for the EO seeker while every other seeker is already discounted. When you select the EO, it only increases the cost by 4 but it still shows it as 8

**To Reproduce**
1. Go to CM-4 missile editor

**Expected behavior**
EO seeker should show a 4 point price

**Comment by stackcollision** [comment]
Point cost when added to the missile is correct, missile components have no way of knowing what missile they are being added to so cost shows the same in the tooltip
