### ISSUE TITLE
Rendezvous breaks stuff

### ISSUE THREAD

**Issue by TexanByTrade** [stackcollision/Nebulous-BugReporting#322]
**Describe the bug**
TG One is en route to a POI. If TG Two tries to rendezvous with One, TG Two can sometimes slingshot way past the POI, causing more errors (the POIs start to drift off their orbits, the calendar date eventually freezes and then ships can't get new move orders anymore, maybe more).

**To Reproduce**
1. Order a TG to a POI, and then order another TG to Rendezvous & Join the first one.
2. Progress a couple turns and enjoy the show.

**Expected behavior**
Not really sure what rendezvousing is supposed to look like.

**Additional context**

**Attachments**
Attach any screenshots, logs, fleet files, etc that may help.

**Comment by d0d0b1rd** [comment]
I've noticed the issue is more common when performing longer transfers, like going from periapsis to apoapsis of an orbit. The fleet that failed to intercept will also be unorderable

I've noticed it can happen when trying to move to a moon as well
