### ISSUE TITLE
Loading a Conquest match from Battle select fails.

### ISSUE THREAD

**Issue by Apocal43** [stackcollision/Nebulous-BugReporting#329]
**Describe the bug**
After saving a Conquest game from the screen where ships are assigned for a battle, attempting to load fails with a stripped-down Conquest UI being presented.

**To Reproduce**
1. Load Conquest savegame given below.
2. After extremely brief loading, see stripped down Conquest UI and no Battle screen.
[New Conquest Game-q03EhQtwnEyTZNmDv9FOZA.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/12194335/New.Conquest.Game-q03EhQtwnEyTZNmDv9FOZA.zip)

**Expected behavior**
Loading into the Battle screen to assign ships to players.

**Attachments**
Attach any screenshots, logs, fleet files, etc that may help.

**Comment by Apocal43** [comment]
I have observed the same behavior from another save, this one taken from the general Conquest layer, rather than the battle screen specifically.
[Uploading Apocal Test Run 4-U1-_GjTB9U2pjot3ZpUiEg.zip…]()

**Comment by stackcollision** [comment]
Can't download the second file, but that first one loads fine for me.  Maybe it was due to a bug I already fixed.  Test in next patch.

**Comment by Apocal43** [comment]
It appears to be all cleared up.
