### ISSUE TITLE
Skirmish UI and performance issues

### ISSUE THREAD

**Issue by Khanage-jmc** [stackcollision/Nebulous-BugReporting#332]
**Describe the bug**
Major UI issues with skirmish loaded from conquest game.
- All ships forced to spawn at the 0,0 point
- Ship models and UI Icons not aligned
- Move order destination appears far away from mouse cursor
- Game resolution and framerate is unexpectedly low

**To Reproduce**
See linked video for full replication.
- Start skirmish game
- Order fleets into hostile area and end turn
- Begin combat
- Observe unexpected behavior

**Expected behavior**
Skirmish in conquest should function as in standalone skirmish game

**Additional context**
4K desktop resolution, powerful gaming PC, 

**Attachments**
Unlisted youtube video: https://www.youtube.com/watch?v=vA9d5_JlvqU
Skirmish starts at 1:00, Deployment at 1:33
Edit: Zipped conquest DB added
[New Conquest Game-wrQ8DQwth0iHu1kKIKEt9g.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/12194788/New.Conquest.Game-wrQ8DQwth0iHu1kKIKEt9g.zip)
Edit2: That conquest DB may be corrupted- it won't load correctly. Tested again with this one and the issue can be replicated:
[Fresh Conquest.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/12194870/Fresh.Conquest.zip)

**Comment by Khanage-jmc** [comment]
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/12194487/Player.log)
Player.log attached. Note that after the video recording ends, the same issue as reported [here ](https://github.com/stackcollision/Nebulous-BugReporting/issues/331) occurred - red error text on exiting skirmish.

**Comment by Khanage-jmc** [comment]
Other players have reported the same issues but without the low resolution.

**Comment by d0d0b1rd** [comment]
I set up an encounter with both sides using nothing but missiles and noticed two issues: 
Firstly, I don't think the custom missiles were loaded, the match ended instantly after decelerating

Secondly, after it kicked me back to the map, I got this screen
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/124643297/ee414cc1-5be2-4187-9652-454ed428ede6)
log file: https://discord.com/channels/409638848302153728/425835550193483784/1134465519269978164

**Comment by Khanage-jmc** [comment]
Confirmed the resolution and UI offset errors also occur on skirmishes started directly from the single-player menu, not just those started from a conquest game.
Low framerate issue did not occur on a single-player skirmish.

**Comment by Khanage-jmc** [comment]
No longer present in 0.4.0.3:230729-0942
