### ISSUE TITLE
Deleting a ship with missiles will remove the template even if the same missile is being used by other ships

### ISSUE THREAD

**Issue by d0d0b1rd** [stackcollision/Nebulous-BugReporting#334]
**To Reproduce**
1. create two ship designs (say, a frigate and cruiser) that use the same missile design
2. Add both designs to the starting conquest fleet, then remove one of the ships (eg, remove the cruiser design)
3. The missile design is no longer present, both in the preview and in the design cost summary (eg, even though the FF uses the same missile, the missile design will be removed when the cruiser is removed)

One additional note: deleting any ship, equipped with missiles or not, will clear the missile design preview cards, but the cost of the missiles still shows up in the design cost

**Comment by titowulk** [comment]
Related note: 

Missile designs removed via this sometimes keep their design cost in the total, even though they are removed.
