### ISSUE TITLE
"Method not implemented" redtext on trying to select "Show Info" for both Task Groups and Task Forces

### ISSUE THREAD

**Issue by GammaRailgun** [stackcollision/Nebulous-BugReporting#338]
**Describe the bug**
On clicking "Show Info" for forces on the map, I got a "Method Not Implemented" error.
I also got InvalidOperationExceptions when trying to measure from an unevaluated track to a friendly map unit.
I also wasn't able to find any option for moving my ships to intercept unevaluated tracks.

**To Reproduce**
1: Open a Conquest game from the main menu (150,000 point limit is the only change from default)
2: Once in the Conquest game, proceed immediately to Faction Identity and Navy Design
3: Switch to editing the CPU faction, only looking at Faction Identity and Navy Design
4: Ready team and start the game
ERROR 1 (Method Not Implemented)
5a: Select a Task Force or Task Group on the map
6a: Right-click the Task Unit
7a: Click "Show Info"
ERROR 2 (Invalid Operation Exception)
5a: Select an unevaluated track
6a: Right-click the track
7a: Click "Measure"
8a: Mouse over a friendly Task Unit with the resulting widget

**Expected behavior**
[N/A]

**Additional context**
This might be a case of user error: I didn't set up faction control roles in the initial setup phase, although I'm not sure whether or not that's actually *necessary* as I was under the High Admiral role.

**Attachments**
LOGFILE:
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/12196647/Player.log)

Ship files included in case it's something wrong with them. They are converted to .txt because Github doesn't like .ship files.
"?" indicates I'm not 100% sure on the exact number of ships I set up in the navy design.

FACTION 1 SHIPS
10 [CH-BM Yang Xiao-Long (Mk 1.0).txt](https://github.com/stackcollision/Nebulous-BugReporting/files/12196697/CH-BM.Yang.Xiao-Long.Mk.1.0.txt)
32 [CL-BT Ruby Rose (Mk 1.0).txt](https://github.com/stackcollision/Nebulous-BugReporting/files/12196692/CL-BT.Ruby.Rose.Mk.1.0.txt)
10 [CL-MI Weiss Schnee (Mk 1.0).txt](https://github.com/stackcollision/Nebulous-BugReporting/files/12196693/CL-MI.Weiss.Schnee.Mk.1.0.txt)
20 [DD-RG Blake Belladonna (Mk 1.0).txt](https://github.com/stackcollision/Nebulous-BugReporting/files/12196694/DD-RG.Blake.Belladonna.Mk.1.0.txt)
38? [FF-SC Qrow Branwen (Mk 1.0).txt](https://github.com/stackcollision/Nebulous-BugReporting/files/12196695/FF-SC.Qrow.Branwen.Mk.1.0.txt)
32 [FL-EW Bumblebee (Mk 1.0).txt](https://github.com/stackcollision/Nebulous-BugReporting/files/12196696/FL-EW.Bumblebee.Mk.1.0.txt)

FACTION 2 SHIPS
5 [BB-BT Salem (Mk 1.0).txt](https://github.com/stackcollision/Nebulous-BugReporting/files/12196765/BB-BT.Salem.Mk.1.0.txt)
11? [CH-RG-BM Cinder Fall (Mk 1.0).txt](https://github.com/stackcollision/Nebulous-BugReporting/files/12196767/CH-RG-BM.Cinder.Fall.Mk.1.0.txt)
18? [DD-BM-MI Adam Taurus (Mk 1.0).txt](https://github.com/stackcollision/Nebulous-BugReporting/files/12196768/DD-BM-MI.Adam.Taurus.Mk.1.0.txt)
38? [FF-EW Arthur Watts (Mk 1.0).txt](https://github.com/stackcollision/Nebulous-BugReporting/files/12196769/FF-EW.Arthur.Watts.Mk.1.0.txt)
21? [FF-MI Tyrian Callows (Mk 1.0).txt](https://github.com/stackcollision/Nebulous-BugReporting/files/12196770/FF-MI.Tyrian.Callows.Mk.1.0.txt)
34? [FF-PK Neopolitan (Mk 1.0).txt](https://github.com/stackcollision/Nebulous-BugReporting/files/12196771/FF-PK.Neopolitan.Mk.1.0.txt)

**Comment by WeebleKeneeble** [comment]
I also had the same error, locked me on the loading screen
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/12202608/Player.log)

**Comment by stackcollision** [comment]
Any NotImplementedException does not need to be reported.  They mean I haven't gotten to that part yet and it's a placeholder/stub.

Weeble, in your case it's because you used the OSP which is not compatible with conquest yet.
