### ISSUE TITLE
redtext and blank starmap after completing skirmish in conquest mode

### ISSUE THREAD

**Issue by Cebasiz** [stackcollision/Nebulous-BugReporting#342]
**Describe the bug**
starmap disappears and redtext generated after exiting victorious skirmish

**To Reproduce**
1. skirmish (just took my fleet, consolidated it and then attacked enemy TF)
2. error

**Expected behavior**
no redtext

**Attachments**

[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/12206909/Player.log)

**Comment by d0d0b1rd** [comment]
had a similar issue: https://github.com/stackcollision/Nebulous-BugReporting/issues/345
