### ISSUE TITLE
Finishing a conquest battleresults in a NullReferenceException and a blank system map

### ISSUE THREAD

**Issue by d0d0b1rd** [stackcollision/Nebulous-BugReporting#345]
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/124643297/6c08099c-543a-4125-81a1-2232e26768ca)
Log file and save file: https://discord.com/channels/409638848302153728/425835550193483784/1134846281689354362

It seems like finishing any conquest battle leads to this problem

**Comment by Krypticon** [comment]
+1 Same outcome
