### ISSUE TITLE
Semi-active Hybrid missiles (Cyclone, Atlatl) with no or any backup seekers does not activate stage seperation.

### ISSUE THREAD

**Issue by Janssendel** [stackcollision/Nebulous-BugReporting#35]
**Describe the bug**
Semi-active Hybrid missiles (Cyclone, Atlatl) with no or any backup seekers does not activate stage seperation. 

**To Reproduce**
1. Go to Missile Designer
2. Click on SGM-H-2XX or SGM-H-3XX missiles and create new missile. Set primary seeker to Semi-active radar. Avionics config. does not matter.
3. Game will say that "WARN: Primary seeker provides direction only, staging will not trigger."

**Expected behavior**
Missile will seperate sprint stage with Semi-active primary seeker.

**Additional context**
Missile will act like normal with illumination from w
![ảnh](https://user-images.githubusercontent.com/61640498/177178551-5ee58a40-04bf-431d-881c-ecde165e8b33.png)
arship. Without illumination, the missile will revert to a Thunderhead-like guidance system with FARS, SARS and SEARS. 

**Attachments**
![ảnh](https://user-images.githubusercontent.com/61640498/177178215-3e38246f-9a8b-4613-aa61-f774124e525f.png)
![ảnh](https://user-images.githubusercontent.com/61640498/177178264-2014eb26-297b-4a27-bc80-3f1cffcfd0f5.png)
![ảnh](https://user-images.githubusercontent.com/61640498/177178307-2658952d-be31-4eb5-be98-ba4227d166d8.png)
![ảnh](https://user-images.githubusercontent.com/61640498/177178331-a5214669-5932-40be-87fb-9f9187ef6b7f.png)
![ảnh](https://user-images.githubusercontent.com/61640498/177178391-837c4ebf-a829-4326-a61f-61759905503d.png)

**Comment by stackcollision** [comment]
Not a bug, missile must know range to target to determine when to stage.  Semi-active seeker does not get range.
