### ISSUE TITLE
When deploying, expected ships replaced by placeholders and unable to deploy. (Phantom Contacts)

### ISSUE THREAD

**Issue by Apocal43** [stackcollision/Nebulous-BugReporting#353]
**Describe the bug**
When attempting to deploy ships, each click on a ship in the deployment bar below instead assigns a formation (A Very Long Ship Name +4) to 0,0. There is no way possible to deploy the actual ships.

**To Reproduce**
(possible, not firm)
1. Fight a battle at a POI and win.
2. Claim POI.
3. Advance turn.
4. See a "phantom" enemy track appear and generate battle.
5. Error happens after accepting and starting the battle as normal.

**Expected behavior**
Normal deployment.

**Additional context**
It appeared to happen when there was no enemy presence at the POI, despite a battle being generated.

**Attachments**
Attach any screenshots, logs, fleet files, etc that may help.
[ApocalTestRun10-altfN_dEPU-lirMp8VFtSQ-DEPLOYBUG.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/12252554/ApocalTestRun10-altfN_dEPU-lirMp8VFtSQ-DEPLOYBUG.zip)
[Deploy Bug Log.txt](https://github.com/stackcollision/Nebulous-BugReporting/files/12252578/Deploy.Bug.Log.txt)

**Comment by Apocal43** [comment]
This appears to be related to the phantom contact issue. Reproducible when engaging phantom contacts but is not maintained in save.

**Comment by d0d0b1rd** [comment]
Tried loading testrun10 and testrun12, both of them are getting similar errors on my end too
