### ISSUE TITLE
Game has completely locked up in the middle of turn three execution phase

### ISSUE THREAD

**Issue by d0d0b1rd** [stackcollision/Nebulous-BugReporting#356]
The conquest game has completely locked up on the system map, AI will not ready their turn, Test Execute Turn doesn't work, and reloading the save doesn't work either

Not sure how to replicate the issue, but the issue persists even after loading the save I've attached.

Issue seemed to occur after attacking an enemy in enemy territory with the same fleet for multiple turns in a row (retreating and reengaging until they were worn down and "killed")

[08-HmZKANrECECgbZS6IAMhjg.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/12255424/08-HmZKANrECECgbZS6IAMhjg.zip)

[Player-prev.log](https://github.com/stackcollision/Nebulous-BugReporting/files/12255417/Player-prev.log)

**Comment by Apocal43** [comment]
I have found this to occur after attempting to engage a "phantom" enemy contact. Save game attached.
[ApocalTestRun11-dhj1-lOBXUal7i-qhiRX8g-ORDER.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/12255639/ApocalTestRun11-dhj1-lOBXUal7i-qhiRX8g-ORDER.zip)
