### ISSUE TITLE
Adding a food rationing subsection to a movement order prevents the fleet from moving

### ISSUE THREAD

**Issue by cannonfodder1** [stackcollision/Nebulous-BugReporting#375]
**Describe the bug**
If a movement order has a rationing subsection attached, the fleet does nothing when Execute Turn is hit. No obvious errors are thrown.

**Expected behavior**
Rationing should have no effect on the behaviour of the fleet on the strategic map.

**Additional context**
Produced in a campaign that was started before the most recent Sept 20th patch

**Comment by stackcollision** [comment]
Not Implemented Exception
