### ISSUE TITLE
Various redtext errors upon loading from conquest to skirmish battle

### ISSUE THREAD

**Issue by cannonfodder1** [stackcollision/Nebulous-BugReporting#386]
**Describe the bug**
Various redtext errors appear upon loading from strategy to tactical, but the loading screen finishes and I can deploy my ships and play out the battle with no obvious problems. All ships are assigned to me, with no squadrons set up. The battle was entered straight off the bat on the first turn, with an order given for a starting TF to go attack an enemy moon, and turn execution immediately after with all other TFs idle.

**Expected behavior**
No redtext when transitioning to a skirmish battle

**Attachments**

[errors-loading-to-skirmish.txt](https://github.com/stackcollision/Nebulous-BugReporting/files/13232399/errors-loading-to-skirmish.txt)

**Comment by stackcollision** [comment]
This appears to be due to you using a ship that was built on the main branch with the updated Masquerade's save data, which is not known on this branch.
