### ISSUE TITLE
Infinite loading screen after finishing skirmish battle by abandoning pursuit

### ISSUE THREAD

**Issue by cannonfodder1** [stackcollision/Nebulous-BugReporting#387]
**Describe the bug**
After beating up the enemy AI on Cliff for a while, the points hit 500 and I won the battle. Almost immediately after the timer appeared, I hit the abandon pursuit button to test that functionality. The battle ended and I went to the loading screen to get back into the strategy map, but the loading screen hung on the Preserving Ship States phase with a single UnityException, something about the Battleship's armour mask. I alt-F4'd after five minutes waiting. Exactly what caused this is hard to pinpoint. There were two battleships in the battle, one of them reactor bloomed, and both of them had reactor blooms appear in close proximity which would have shredded all their armour.

**Expected behavior**
Able to transition back from tactical to strategy map with no errors.

**Attachments**

[abandon-pursuit-lock.txt](https://github.com/stackcollision/Nebulous-BugReporting/files/13232440/abandon-pursuit-lock.txt)

![20231101154027_1](https://github.com/stackcollision/Nebulous-BugReporting/assets/1369684/4f3007c2-5763-42ef-9018-18121b21a046)

**Comment by stackcollision** [comment]
Dupicate of #389
