### ISSUE TITLE
Intercept Subsection Preventing Order Execution

### ISSUE THREAD

**Issue by eCorbeau** [stackcollision/Nebulous-BugReporting#388]
**Describe the bug**
Adding an enemy intercept subsection to a move order prevents execution of that move order; the fleet simply sits in place.

**To Reproduce**
1. Issue a move order to the fleet (default or custom burn times)
2. Add an "Intercept Enemy" subsection (default or custom settings, having tried several combinations of each option).

**Expected behavior**
The fleet would execute the move order, deviating to pursue detected enemy contacts within the given parameters.

**Comment by stackcollision** [comment]
If you error you see if NotImplementedException, that is not meant to be used yet and is a placeholder for me to remember to finish it.
