### ISSUE TITLE
From the ESC menu, Load Game and Settings do not work.

### ISSUE THREAD

**Issue by Apocal43** [stackcollision/Nebulous-BugReporting#400]
**Describe the bug**
On the Conquest map, pressing ESC and selecting either Load Game or Settings does nothing but play the click sound.

**To Reproduce**
1. Load into Conquest
2. Press ESC
3. Click on either Load Game or Settings; it will play the appropriate sound.
4. Nothing else will happen

**Expected behavior**
Either the load game or settings screens to open.

**Comment by ShadowLotus232** [comment]
Central post covers issue #367
