### ISSUE TITLE
Loading faction template doesn't account for how Trait card modifies cost in ready up button

### ISSUE THREAD

**Issue by captainwolfer** [stackcollision/Nebulous-BugReporting#403]
**Describe the bug**
I loaded a faction template that had the "Profuse Procurement" trait card and a total cost of 99,950 pts. It would not let me ready up, it said "exceeding point limit". I removed the "Profuse Procurement" trait and then re-added it, and then I could ready up.

**To Reproduce**
1. Load faction template that would be over total cost if you were not using the Profuse Procurement Trait
2. Observe how although Allocated points on the navy design screen is under the limit, it doesn't let you ready up.
3. Remove and then add Profuse Procurement, which enables ability ready up

**Attachments**
![Screenshot 2024-01-11 151811](https://github.com/stackcollision/Nebulous-BugReporting/assets/108598089/827677c1-6e58-4776-859b-3f970408ac0e)

**Comment by Snowblind111** [comment]
Adjusting the ship count e.g. decreasing then increasing the number of a particular design by 1 also fixes the issue.
