### ISSUE TITLE
Masqueraded ships in skirmish do not present their fake identity to intel

### ISSUE THREAD

**Issue by cannonfodder1** [stackcollision/Nebulous-BugReporting#420]
**Describe the bug**
Enemy team had Solomons masquerading as Axfords, but when we engaged them in skirmish, they showed as Solomons to us despite never coming close enough to visually reveal them, nor ever firing missiles at them.

**Attachments**
See 43:59 in the recording: https://www.youtube.com/watch?v=huNgHGxLFZU
[conqtest.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14000559/conqtest.log)

**Comment by RyMarq** [comment]
Specific issue seems to be that ships do not save base settings correctly, leading to masquerade calibrated wrong and weapon groups not loading.
