### ISSUE TITLE
Officer info panel only shows level and skills for the billet they are currently in

### ISSUE THREAD

**Issue by cannonfodder1** [stackcollision/Nebulous-BugReporting#424]
**Describe the bug**
Opening an officer's info panel to inspect their skills and levels in the various billets only shows the billet they are currently stationed in. Weapons officers only show their weapon level and skills, commanding officers only show their command level and the notice that it applies all the skills below (of which there are none), etc. Also, everyone's skill level in every billet is zero. This was before the first battle and before any exit/rejoin so it is possible that this issue only takes place right after the game is setup.

**Attachments**
See 14:13 in the recording: https://www.youtube.com/watch?v=huNgHGxLFZU
[conqtest.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14000559/conqtest.log)

**Comment by Apocal43** [comment]
This appears to be the same bug as described here:
https://github.com/stackcollision/Nebulous-BugReporting/issues/418
