### ISSUE TITLE
Error after conquest battle, skipped retreat phase

### ISSUE THREAD

**Issue by Khanage-jmc** [stackcollision/Nebulous-BugReporting#435]
**Describe the bug**
After completing a conquest battle, the game skipped the retreat phase and the defenders lost all of their ships that had not manually retreated already. Attached errors were also seen on return to the conquest map.

**Expected behavior**
Battle should have included retreat phase.

**Attachments**
Attach any screenshots, logs, fleet files, etc that may help.
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14036590/Player.log)

**Comment by TexanByTrade** [comment]
Host Log file: 
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14036609/Player.log)

**Comment by Snowblind111** [comment]
Here's my logs after the error
[Player.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14036610/Player.zip)
