### ISSUE TITLE
Chat Character Limit Broken

### ISSUE THREAD

**Issue by Highrs** [stackcollision/Nebulous-BugReporting#44]
**Describe the bug**
The character limit on in-match chat is not functioning.

**To Reproduce**
1. Pasting in a large enough paragraph, as one or by parts.

![image](https://user-images.githubusercontent.com/8764280/177243648-69f52009-34c0-4a99-a2c6-9cb60a5421f6.png)

**Comment by DesertSaker** [comment]
hi hello hey howdy hi
