### ISSUE TITLE
Corkscrew on S3 causes complete miss

### ISSUE THREAD

**Issue by vren55** [stackcollision/Nebulous-BugReporting#46]
**Describe the bug**
S3 single stage missiles set to corkscrew terminal behaviour complete miss without hitting target

**To Reproduce**
1. Load fleet an S3 pilum style missile and bullseye radar
2. Set terminal behaviour to corkscrew
3. Load ships, fire S3 missiles at stationary target. Missiles will corkscrew and miss completely

**Expected behavior**
I expected the corkscrew terminal behavior to be active until last moment where missile calculates track and brings the missile to target, and if there were misses to be a few, not all THE missiles to miss.

**Attachments**
Attach any screenshots, logs, fleet files, etc that may help.
![20220704213528_1](https://user-images.githubusercontent.com/45466969/177250253-e30c5fd0-487f-4945-8356-c817b62101f4.jpg)
![20220704213534_1](https://user-images.githubusercontent.com/45466969/177250259-4209cb63-6b5a-4db1-988a-94e9ee1f3e5a.jpg)

**Comment by TexanByTrade** [comment]
Do you have low maneuverability? It works way better if you up that in my experience

**Comment by vren55** [comment]
> Do you have low maneuverability? It works way better if you up that in my experience

That's possible but shouldn't the tracking of the missile compensate? I would have expected a miss with a maneuvering target but not a stationary one...

**Comment by vren55** [comment]
My point being... yes maneuverability should affect a missiles ability to stay on target with a moving vessel but... a stationary one?

**Comment by sdk2013** [comment]
I was able to replicate this bug in testing.
