### ISSUE TITLE
Ships landing at Jewel's Rest (gas giant) fly off into space somewhere

### ISSUE THREAD

**Issue by TexanByTrade** [stackcollision/Nebulous-BugReporting#463]
**Describe the bug**
Watch TG Chromium in the vid below. As soon as it lands at Jewel's Rest, it pops out of existence (redtext might be related. I _think_ it is line 1397 in the log). I later found Chromium far away on the map. It only appeared far out, but I could move it just fine. 

**Attachments**
https://youtu.be/SR64P2u0wfg?si=sk-QXhCF6TiE3T3L&t=2373

[Player-prev - Copy.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14205766/Player-prev.-.Copy.log)

**Comment by ShadowLotus232** [comment]
Central post also covers issue #523
