### ISSUE TITLE
POV "P" Button causing visual overload when backed out of option.

### ISSUE THREAD

**Issue by thebluehaloguy** [stackcollision/Nebulous-BugReporting#47]
**Describe the bug**
When you go into the POV mode on a ship, take a bunch of fire from guns, and then back out of the POV, when you back out all of the damage loads at once.

**To Reproduce**
1. Load a game, I had a BB and the enemy had lots of 120mm frigates
2. Go into POV mode
3. Wait for your ship to take a lot of fire
4. Exit POV mode and watch as all the damage you took loads all at once.

**Expected behavior**
It was expected when I back out of POV mode that old damage wouldn't visually render.

**Additional context**
In the video, when I leave POV mode, notice the massive plume of explosions on my ship and then watch as it goes back to normal as the fire continues at its normal rate.

**Attachments**

https://user-images.githubusercontent.com/108600554/177256726-a9bb8a82-770b-452c-9c1e-4f50e93eea38.mp4

**Comment by NicholasZonenberg** [comment]
I believe I've seen this also on live when exiting tactical view as well.
