### ISSUE TITLE
Officers can be moved between two ships located at different POIs

### ISSUE THREAD

**Issue by cannonfodder1** [stackcollision/Nebulous-BugReporting#470]
**Describe the bug**
Title, check if can reproduce, did not see it myself personally, possible that the reporter mistook two fleets at same POI as being in different locations, verbal exchange during discovery is at 11:40 here: https://www.youtube.com/watch?v=wDlMvOu2-kI

**Comment by TexanByTrade** [comment]
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/50686643/ac6b13f5-ada4-41b6-a233-cbd62d5c9806)
I could not reproduce.

**Comment by stackcollision** [comment]
Can't reproduce.
