### ISSUE TITLE
Red Text Upon Server Join, Issues with Empty TACSIT

### ISSUE THREAD

**Issue by Apocal43** [stackcollision/Nebulous-BugReporting#487]
**Describe the bug**
Red text appeared upon joining a server, TACSIT was completely empty.

**Attachments**

OnDeserialize failed Exception=System.MissingMethodException (see below) object=Map Track(Clone) component=Conquest.Sensors.MapTrack sceneId=0 length=124. Possible Reasons:
  * Do Conquest.Sensors.MapTrack's OnSerialize and OnDeserialize calls write the same amount of data(124 bytes)? 
  * Was there an exception in Conquest.Sensors.MapTrack's OnSerialize/OnDeserialize code?
  * Are the server and client the exact same project?
  * Maybe this OnDeserialize call was meant for another GameObject? The sceneIds can easily get out of sync if the Hierarchy was modified only in the client OR the server. Try rebuilding both.

Exception System.MissingMethodException: Default constructor not found for type Conquest.Map.DynamicPositioning.SimpleMovementPositionSource
  at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x0007b] in <695d1cc93cca45069c528c15c9fdd749>:0

**Comment by cannonfodder1** [comment]
Similar errors also experienced upon executing a turn in this same game, see bottom of this log, saved at the end of the execution phase:
[turnexecutionerrors.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14327948/turnexecutionerrors.log)
