### ISSUE TITLE
2x Enemy Tracks appear drawn on top of each other

### ISSUE THREAD

**Issue by Khanage-jmc** [stackcollision/Nebulous-BugReporting#489]
**Describe the bug**
2x tracks appear in the same position, can only be identified by labels doubling up:
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/108599226/6118c1be-363e-4f26-afb3-3a27719a0035)

**To Reproduce**
Not clear yet - noticed mid-way through a conquest game.

**Expected behavior**
Tracks in the same position should be offset so they aren't confused for a single track.

**Comment by Khanage-jmc** [comment]
Not dependent on zoom scale:
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/108599226/e2a99fff-89a1-427c-85f6-f1c50e3c3bc4)

**Comment by ShadowLotus232** [comment]
Same thing as issue #488 : the tracks are just on top of one another. This is not a bug, it's two separate tracks leaving at the same time from the same POI to the same POI. 

It may be a good idea to have the tracks explode out temporarily if clicked or moused over - like the context menu in blender.
