### ISSUE TITLE
"Error occured while saving game state. Attempting rollback."

### ISSUE THREAD

**Issue by TexanByTrade** [stackcollision/Nebulous-BugReporting#492]
**Describe the bug**
As a battle started loading, I (host) got the red text below about failing to save and attempting to rollback. The battle happened on 16 SEP, but after the battle was finished, we got no battle report, and the game indeed was rolled back to 11 SEP  :((((

**To Reproduce**
Unknown.

**Attachments**
[bugSnippet.txt](https://github.com/stackcollision/Nebulous-BugReporting/files/14328908/bugSnippet.txt)

(full log: 
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14328911/Player.log) , line 2022)

**Comment by Khanage-jmc** [comment]
[Uploading Player.log…]()
Player log attached

**Comment by ShadowLotus232** [comment]
Central post also covers issues #438 and #571
