### ISSUE TITLE
NotImplementedException when trying to use right-click on various celestial objects; seemed to go away when opening Team Roster

### ISSUE THREAD

**Issue by TexanByTrade** [stackcollision/Nebulous-BugReporting#494]
**Describe the bug**
Trying to right-click on a Factory or moons occasionally gave the redtext pasted below. By opening and closing the Team Roster, I was then able to right-click again.

**To Reproduce**
Unknown. It happened at random.

**Attachments**
[message(2).txt](https://github.com/stackcollision/Nebulous-BugReporting/files/14344887/message.2.txt)

**Comment by stackcollision** [comment]
Ignore these exceptions, it means I haven't gotten to the functionality yet
