### ISSUE TITLE
Placing ships into GRAVING berths while other ships occupy the berths will crash the game.

### ISSUE THREAD

**Issue by Apocal43** [stackcollision/Nebulous-BugReporting#498]
**Describe the bug**
Attempting to place mobile ships into the graving berths of a shipyard while other ships are still in active graving status (purple G) will cause the game to crash.

**To Reproduce**
1. Select damaged ships at a shipyard POI.
2. Enter shipyard, make sure GRAVING is selected for work.
3. Press Enter Port.
4. See error: crash to desktop.

**Additional context**
In my video, the ships should've been out of graving status and free to shift berths (it was like 6 OCT) but still had a purple G and crashed the game.

**Attachments**
[Attach any screenshots, logs, fleet files, etc that may help.](https://youtu.be/DW4iO03fPN4) (45 seconds)

**Comment by stackcollision** [comment]
Can't reproduce without save file

**Comment by Apocal43** [comment]
[Apocal Test Run 62-HfdPIWaP2EGOd54ksopYMw CRASH TO DESKTOP GRAVING.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14594421/Apocal.Test.Run.62-HfdPIWaP2EGOd54ksopYMw.CRASH.TO.DESKTOP.GRAVING.zip)

**Comment by ignifluous** [comment]
Just got the same thing. Singleplayer, minor powers. Turn tasking phase had just started, grabbed a damaged ship I had sent to the shipyard, "enter port". It auto-filled the field with "graving" as the purpose, so I thought maybe one of the berths had come available, or that it would enter a queue for the next available berth or something ...... and CTD.

1) Load save, resume turn execution
2) When complete, find TACSIT -> Independent -> AAAA Steak Acute (heavily damaged CL)
2) Enter port at NAVSHPYD Amethyst
3) Purpose "Graving" is auto-selected
4) Accept.
5) CTD!

Full log to that point: 
[2024 03 24 CTD graving while berths full.txt](https://github.com/stackcollision/Nebulous-BugReporting/files/14734877/2024.03.24.CTD.graving.while.berths.full.txt)

Save:
[9-graving while full.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14734882/9-graving.while.full.zip)

**Comment by ShadowLotus232** [comment]
Central post _MAY_ cover issue #486

**Comment by Apocal43** [comment]
Update: reproduced WITHOUT ships in a graving status (purple G). Multiplayer game crashed when ships placed into graving with the graving piers empty. Log from host doesn't seem to contain any errors.
[Player(1).log](https://github.com/stackcollision/Nebulous-BugReporting/files/14789478/Player.1.log)
[OCE_Game_3-H_RzTDx2f06ClvTg7NpQkQ GRAVING CRASHES GAME.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14789482/OCE_Game_3-H_RzTDx2f06ClvTg7NpQkQ.GRAVING.CRASHES.GAME.zip)
