### ISSUE TITLE
Weird quirks with the missile editor

### ISSUE THREAD

**Issue by Enderminion1** [stackcollision/Nebulous-BugReporting#50]
**Describe the bug**
While attempting to make a missile of exactly 200m/s speed to try and make a 3pt semi active I stumbled across a weird break point where one step towards top speed shifted the missile from 199m/s to 201m/s (and vice versa)

**To Reproduce**
1. Go to Missile Editor
2. Click on Engine
3.a adjust slider to one of the upper edges (top speed/burn time or top speed/agility)
3.b Attempt to increment missile speed by 1m/s
4. See error(s)

**Expected behavior**
Missile speed increments by 1m/s for every step towards Top Speed.
**Additional context**
It is possible to make a missile travelling 200m/s exactly iff the slider is on one of the extremes.
![image](https://user-images.githubusercontent.com/108599751/177411317-dbccbdd6-a5f3-4480-9cbf-c7efd0dc9f59.png)
It is not possible to make a missile travelling 200m/s exactly if the slider is not on such an extreme.

**Comment by stackcollision** [comment]
Not a bug, due to resolution of the slider.
