### ISSUE TITLE
Rare Metall doesn't show up in logi window

### ISSUE THREAD

**Issue by gwaca1** [stackcollision/Nebulous-BugReporting#512]
**Describe the bug**
The station has rare ores pressent but they don't show up in the logi route editor as available

**To Reproduce**

**Expected behavior**
Available rare metals show up when available 

**Additional context**

**Attachments**
![grafik](https://github.com/stackcollision/Nebulous-BugReporting/assets/89867252/b7f518c1-17b2-4a09-a5b6-07be489f4301)
[Test-tTSSnmamd0GZIbvrIp9DaA.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14622712/Test-tTSSnmamd0GZIbvrIp9DaA.zip)

**Comment by ShadowLotus232** [comment]
Reproduced: minor powers, single player, complex logistics

(untested in multiplayer or on simple logistics)

1. Upon starting game look at a refinery's storage and the default shipping manifest.
2. Execute turn
3. Reopen windows; see issue.

Storage will show the newly produced materials, but the manifest will not reflect the change. 
Creating a new shipping manifest also does not reflect the newly available resources.
Executing a second turn and allowing the default shipment to leave does not allow manifests to reflect the change.
Show Only Available does not display correct values.

Performing the same steps after several turns on a different refinery that you haven't touched populates it's shipping manifests with the correct numbers, but they will not update to reflect any change after executing another turn.

Effectively the shipping manifest "on station" column is frozen to whatever the value was when you first made the request for information.

![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/34362934/16b3540c-08e9-498e-a060-2bb9963b7adf)
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/34362934/51e96879-c375-4504-a50d-20119cc45786)
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/34362934/1e25f02a-c5bc-4e2c-a9a7-98057b58f74a)
