### ISSUE TITLE
When attempting to set PDMSL policy across the formation, option is disabled

### ISSUE THREAD

**Issue by yannisvetster** [stackcollision/Nebulous-BugReporting#52]
**Describe the bug**
Can not set the PDMSL policy of a formation at once.

**To Reproduce**
1. Using supplied fleet file
2. Load into game
3. Attempt to set the policy of the formation, observe that the box is greyed out despite Ship 8 having PDMSL.

**Expected behavior**
Can set the PDMSL policy of a formation at once

**Additional context**
N/A

**Attachments**
[Fleet File](https://github.com/stackcollision/Nebulous-BugReporting/files/9050093/mmm.txt)
[Video demonstration of the issue](https://streamable.com/p8y3vr)

**Comment by stackcollision** [comment]
Can you do this on the main branch?  I can't remember.

**Comment by yannisvetster** [comment]
Tested just now, nope.
