### ISSUE TITLE
Siren contact reportedly and visibily intact in SAR, despite absloutely dying save for a mercator in the battle.

### ISSUE THREAD

**Issue by prophetb1** [stackcollision/Nebulous-BugReporting#522]
**Describe the bug**
Siren 04 in SAR has an intact composition with up-to-date SAR, down to the minute of the save, September 07, 497, 15:30, which should only have one surviving Mercator after suffering horrible defeat in battle.

**To Reproduce**
1. Fight battle
2. Kill ships and win
3. Oh no, some escape!
4. SAR shows all ships intact.

**Expected behavior**
SAR should've updated to the measley survivor count

**Additional context**
Not the first time observed, after the first battle of Game 14 you can also see the SAR contacts of the first battle intact.

**Attachments**
Attach any screenshots, logs, fleet files, etc that
![20240316223715_1](https://github.com/stackcollision/Nebulous-BugReporting/assets/110350899/388af9a6-88e6-419f-b929-3954cf3eac83)
 may help.

**Comment by ignifluous** [comment]
similar to #581
