### ISSUE TITLE
One wall later

### ISSUE THREAD

**Issue by CaptMediocre** [stackcollision/Nebulous-BugReporting#523]
**Describe the bug**
I don't know what happened, if I'm honest. I had two fleets going to the gas platforms in an attempt to cap both in one turn. And this was given. First error of the play session. Seemingly no actual reason. 
![Uploading Screenshot (150).png…]()

**To Reproduce**

**Expected behavior**

**Additional context**

**Attachments**
Attach any screenshots, logs, fleet files, etc that may help.

**Comment by SirPoopit** [comment]
[New Conquest Game.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14625689/New.Conquest.Game.zip)
and here's the save file
