### ISSUE TITLE
Ships and Missiles not spawning into the start of the match.

### ISSUE THREAD

**Issue by Ossius** [stackcollision/Nebulous-BugReporting#535]
**Description:** 
It seems when spawning into our match we are missing the Solomon flag post vessels.  The Axford X Ford is missing torpedoes on its VLS-3 bank.  In the possible loadout on the Axford it doesn't even list the VLS-3 as out of ammo, the ammo doesn't even appear 0/10 for example.

Our Team 2 "The Beef" Designs were as follows:
* 2 Solomons - Two flag posts.
* 2 axes
* 2 destroyers
* 1 light
* 3 frigates
* 1 sprinter
* Game settings: 1 day turn - 75k naval cost Minor powers. Complex logistics 

**To Reproduce**
Create a loadout using our beef team file in team 2.  Reproduce the game settings.

**Expected behavior**
All our ships should be able to spawn in.  This did not occur for team 2.  We are missing Solomons both in task force and in port.  The Axford on team 2 should have a torpedo loadout.  The Torpedo loadout in the standard combat load and can't be added.  The missile is researched and can't be produced.  

**Attachments**
Attached Image showing Solomon's listed in design but not in the task forces and standard combat loadout for a new Axe not having Torpedoes available.
<details>
  <summary>Screen Shots</summary>

![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/19178733/3d657e89-4366-43ee-8cea-c40a291ebead)
  
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/19178733/516ad7d1-95b1-4f6d-8187-cb906bdbea04)

</details>

Attaching 2 saves.
[2 Saves.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14628186/2.Saves.zip)

Attaching Fleet loadout for Team 2 where the bug was seen:
[Team BEEF.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14628193/Team.BEEF.zip)

**Comment by CaptMediocre** [comment]
Adding to this, I tried cracking a singleplayer on and no capital ships spawned. Not a one. 
![Screenshot (153)](https://github.com/stackcollision/Nebulous-BugReporting/assets/163549867/24ef4604-5d53-4bfd-8c09-e6dc71603086)
[Mediocre Log.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14628907/Mediocre.Log.zip)

**Comment by CaptMediocre** [comment]
After verifying game files and trying another conquest game, I ended up just having my BB not spawn. So it seems whatever gremlin in the code doesn't want me specifically to have battleships. 
[WHERE IS MY BATTLE SHIP.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14628933/WHERE.IS.MY.BATTLE.SHIP.zip)
![Screenshot (154)](https://github.com/stackcollision/Nebulous-BugReporting/assets/163549867/e50c3ca3-ae8a-42d9-900e-12e1ae9976e9)
![Screenshot (155)](https://github.com/stackcollision/Nebulous-BugReporting/assets/163549867/1acb8ce3-a521-492d-9ebe-d5021fb853ec)
![Screenshot (156)](https://github.com/stackcollision/Nebulous-BugReporting/assets/163549867/a5298b8a-ba7d-42a4-af98-1e1a57e918bd)

**Comment by Raw227** [comment]
[A normal game -gOA48116M0SNMt_tEBgRtg.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14641934/A.normal.game.-gOA48116M0SNMt_tEBgRtg.zip)
Another game where this happened

**Comment by Raw227** [comment]
How to replicate 
https://github.com/stackcollision/Nebulous-BugReporting/issues/545#issue-2194715146
