### ISSUE TITLE
120mm HERPF penetration and damage.

### ISSUE THREAD

**Issue by AhriiIsHot** [stackcollision/Nebulous-BugReporting#54]
**Describe the bug**
This might not be a bug and I might just be stupid but it seems off.
A fully built gun BBs components, external and internal were ignited and damaged by gun frigates running 120mm HERPF, and eventually, it instantly stacked critical events on the ship's reactors without doing any significant damage or visual penetration of the armor.

**To Reproduce**
1. Take fully built gun bb on shooting range against a single AI
2. Stack 10 AI controlled 4x gun frigates on the enemy team
3. Start the game and just watch your DC screen.

**Expected behavior**
120mm HERPF not to be capable of igniting components on a BB without penetrating the armor, or instantly stacking critical events on them. I don't think it even gets near the penetration value required.

**Additional context**
Did the same thing to gun CLs within a similar timeframe

**Attachments**
[1X BBTEST.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/9051235/1X.BBTEST.zip) [Gun BB used]
[1X GUNFRIG.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/9051238/1X.GUNFRIG.zip) [Gun frigates used]

**Comment by YoloWingPixie** [comment]
Adding to this, 250 RPF does the same thing.

**Comment by AhriiIsHot** [comment]
Confirmed that 250mm HERPF does the exact same thing, stacks crit events without armor penetration.
