### ISSUE TITLE
Premature battle end 

### ISSUE THREAD

**Issue by Raw227** [stackcollision/Nebulous-BugReporting#540]
While both teams still had many combat-capable ships alive on the map, the battle ended with all of the ships that were still on the map from the losing team appearing "Evacuated" in the ARR.  

To Reproduce
see comment 

Expected behavior
The "Mop up" phase continues until all ships are off the map, destroyed, or the timer runs out. 

Additional context
There was a single battle before this one in the turn. Several players went out of sync, having to rejoin the lobby beforehand. 
Host jraamus
Osseon and Mediocre pressed "Abandon pursuit" 

Player logs, saves, and video
Attachments 
https://youtu.be/f1FK7OfPV34?t=6462
[player logs.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14629256/player.logs.zip)
[Game16_2024-03-17-II-W6fF_LKo3Ue5Kd20PebGUQ.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14629257/Game16_2024-03-17-II-W6fF_LKo3Ue5Kd20PebGUQ.zip)

**Comment by NaLeslie** [comment]
### To Reproduce:
-Host and at least one person on team 1
-at least one player on team 2
-team 2 attacks team 1
-team 1 loses on caps
-battle ends once host evacs all of their ships, regardless of any allied players' ships still in the battlespace and the timer

https://youtu.be/KkIJlOOv4t0

Possibly related: Bug #543

**Comment by ShadowLotus232** [comment]
Central post covers issue #435 

Problem may be that the game only checks if the host has combat capable ships; I think Darg was saying something about that.

**Comment by SecretMink** [comment]
Just had something similar happen to myself, except it was triggered by the losing team full killing one of the winning team's frigates. Both sides had many combat capable ships still in play

**Comment by Dargaribdus** [comment]
Here's a timestamp for this happening in game #25. My best guess is that the ship got knocked OUT OF POWER or NOT UNDER CONTROL for a split second and that ended the battle.

https://youtu.be/lTVYSV4lVl8?t=3745
