### ISSUE TITLE
NRE on saving and then exiting from GP to Main Menu

### ISSUE THREAD

**Issue by Dargaribdus** [stackcollision/Nebulous-BugReporting#543]
**Describe the bug**
NRE on saving and then exiting from GP to Main Menu.

**Additional context**
All I did before exiting was reorganize and give movement orders to the fleets at Sidra and Shotel, and set S2 and S3H production lines for Emerald and Amethyst factories. 

**Attachments**
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14641315/Player.log)
[Great Power Test-YPKogBTaJ0641q-jjRmF_w.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14641339/Great.Power.Test-YPKogBTaJ0641q-jjRmF_w.zip)

**Comment by ShadowLotus232** [comment]
Central post also covers issue #528. The above mention from issue 540 was a typo and should be ignored.
