### ISSUE TITLE
Desync at battle start, likely due to having no ships under control

### ISSUE THREAD

**Issue by Spedicyulous** [stackcollision/Nebulous-BugReporting#544]
**Describe the bug**
Client desyncs at start of battle, believed cause is from having no ships under control. Issue occurred 3 times, each a different player, in 2 separate battles. Issue is not guaranteed, seems to be 50/50 chance of happening.

**To Reproduce**
Initiate a battle in which your client is not controlling any ships. Must be in multiplayer to do so.

**Expected behavior**
Expected to load into battle with nothing under control but still able to interact/spectate. Some players that also had nothing under control were able load in as expected, but not all.

**Attachments**
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/163689886/7c78000e-11ee-46fd-95fb-aff834ba2d0b)
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14643135/Player.log)

**Comment by Raw227** [comment]
[A normal game -gOA48116M0SNMt_tEBgRtg (2).zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14643954/A.normal.game.-gOA48116M0SNMt_tEBgRtg.2.zip)
[Game 18 logs.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14643955/Game.18.logs.zip)
Logs for most players and the save video will be uploaded tomorrow

**Comment by ShadowLotus232** [comment]
Central post covers issue #467
