### ISSUE TITLE
Ship designs with only a single hull do not spawn 

### ISSUE THREAD

**Issue by Apocal43** [stackcollision/Nebulous-BugReporting#545]
**Describe the bug**
If a design is added to the Navy Design but only has one hull, it will not spawn into Conquest at all.

**To Reproduce**
1. Load attached save game in the Setup phase.
2. Hit Ready.
3. Conquest will load, see error: none of the single ships will be present.

**Attachments**
https://youtu.be/ZxybCbKYSy8 (2:30)
![disappearing ships 1](https://github.com/stackcollision/Nebulous-BugReporting/assets/43554459/f541e59c-f4a1-4043-8ab7-40ccd23d80c8)
![disappearing ships 2](https://github.com/stackcollision/Nebulous-BugReporting/assets/43554459/68512908-0c97-462a-b7fc-11343f113dd3)
[Apocal Test Run 73-NrCwkJFD0kG93XBIliHZpA.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14649880/Apocal.Test.Run.73-NrCwkJFD0kG93XBIliHZpA.zip)

**Comment by ShadowLotus232** [comment]
Save files affected by this issue straight up do not contain the ships with only one instance that are supposed to be there. The issue is in the initial saving of the file after setup completion.

**Comment by ShadowLotus232** [comment]
Central post also covers issue #535
