### ISSUE TITLE
Players not Appearing/incorrectly appearing in chat "Sidebar"  

### ISSUE THREAD

**Issue by Raw227** [stackcollision/Nebulous-BugReporting#546]
Describe the bug
The chat displayed a player on team 2 (Sarn) as being on team 1 but was displayed correctly in the actual chat box. A short time later, several players in the lobby didn't appear in the "sidebar," but their messages were visible; rehosting the lobby fixed the issue. 

To Reproduce
?

Expected behavior
All players appear in the "sidebar" on the correct teams 

Additional context
Raw was the host 

Attachments
https://youtu.be/9HbtqiuXt3I?si=Hx0bQQ9ITmjFbJIs&t=897 The first instance of the bug is at 14:55 and the Second is at 35:18
[Game 18 logs.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14652439/Game.18.logs.zip)
![Visual bug 2](https://github.com/stackcollision/Nebulous-BugReporting/assets/163604224/3b2b2142-df14-4ae4-b0dd-a9b59c515716)
![Visual bug](https://github.com/stackcollision/Nebulous-BugReporting/assets/163604224/10f45de1-e3f0-4255-ac7a-8ae9b98001a1)

**Comment by Raw227** [comment]
Another instance of this issue 
![Bug image](https://github.com/stackcollision/Nebulous-BugReporting/assets/163604224/a7ee44de-5972-4f91-9e9a-4c70cb8164a9)
https://youtu.be/1WnsC1SzJCg?si=-dJHQjX0_5IfYtYi&t=965 
![Correct image](https://github.com/stackcollision/Nebulous-BugReporting/assets/163604224/d4a7d6ec-c1a7-4051-9261-b10d86276b0d)
https://youtu.be/1WnsC1SzJCg?si=hZQlDrjRxTRxFgm4&t=1055 
[Raw game 12 log.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14724077/Raw.game.12.log.zip)

**Comment by ShadowLotus232** [comment]
Central post covers issue #421
