### ISSUE TITLE
Massive wall of Out of Range Exceptions While Attempting to Find other bugs

### ISSUE THREAD

**Issue by Dargaribdus** [stackcollision/Nebulous-BugReporting#549]
I'm not sure exactly what this is or how it happened. I readied up after doing literally nothing to the game then got the log you see below.  Lotus and I were in an MP game. Sorry for not being able to provide more information, I am extremely out of my depth for either understanding this or attempting to reproduce it.

**Attachments**
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14654935/Player.log)

**Comment by ShadowLotus232** [comment]
We started a minor powers game. Darg did nothing but ready, I issued a single move order to a single TG and readied. I was the host and experienced no issue, Darg started getting the IndeOutOfRangeException spam once the turn began to execute.

By the looks of the log the game desynced in reference to a new cargo ship? I'm not sure how reproducible that is though, unfortunately :/
