### ISSUE TITLE
NRE spam before accepting/declining battle

### ISSUE THREAD

**Issue by Dargaribdus** [stackcollision/Nebulous-BugReporting#562]
**Describe the bug**
I received many NREs once an encounter procced. I cannot parse these on my own. Sorry. We were in the Orbit of Jade when it occured, executing Turn 2.

Attachments
[Game 12-_F-LzBmS5UKQFAbpSy41ZQ.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14715420/Game.12-_F-LzBmS5UKQFAbpSy41ZQ.zip)
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14715424/Player.log)

**Comment by Dargaribdus** [comment]
I recieved some MREs after starting the match
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14715441/Player.log)

**Comment by Raw227** [comment]
My version of the bug described 
[Raw game 12 log.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14726722/Raw.game.12.log.zip)
![NRE on battle start](https://github.com/stackcollision/Nebulous-BugReporting/assets/163604224/79e92770-7b66-4de2-9689-c74d5d6af6ab)
https://youtu.be/1WnsC1SzJCg?si=o2HRSfg-yF8HuYkm&t=10440 2:54:00
