### ISSUE TITLE
tons of Steam and networking errors on battle encounter start

### ISSUE THREAD

**Issue by Dargaribdus** [stackcollision/Nebulous-BugReporting#566]
**Describe the bug**
tons of Steam and networking errors on battle encounter start

**Expected behavior**
The ability to use the battle UI

**Additional context**
I and no one else on my team were able to choose to accept or decline battle, the game autoaccepted. 

**Attachments**
Attach any screenshots, logs, fleet files, etc that may help.
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14716275/Player.log)

**Comment by Dargaribdus** [comment]
Another MRE on battle start
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14716319/Player.log)

**Comment by Cebasiz** [comment]
> Another MRE on battle start [Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14716319/Player.log)

tasty
