### ISSUE TITLE
Fuel pier, despite existing, does not appear in the berth schedule of NAVSHIPYRD SHOTEL (great powers)

### ISSUE THREAD

**Issue by Cebasiz** [stackcollision/Nebulous-BugReporting#568]
**Describe the bug**
Fuel pier exists, but it does not appear in the berth schedule even if ships are being fueled at the pier(s) 

**Expected behavior**
Berth schedule should show arming/fueling activity
**Additional context**
game 12 turn 4(?)

**Attachments**

![fueling pier](https://github.com/stackcollision/Nebulous-BugReporting/assets/10738550/8bdfef44-da00-46ac-83e3-85808fe0314d)
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14716882/Player.log)

**Comment by stackcollision** [comment]
It's there, you have to scroll down
