### ISSUE TITLE
All POIs disappear 

### ISSUE THREAD

**Issue by Raw227** [stackcollision/Nebulous-BugReporting#573]
All POI of interest disappear. I can still see "zones of influence, orbits, and fleets, but not stations or the orbital bodies themselves. Fixed by reconnecting 
[Raw game 12 log.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14726844/Raw.game.12.log.zip)  
POIs Gone](https://github.com/stackcollision/Nebulous-BugReporting/assets/163604224/ecf0f26c-fc56-4efe-8ef7-0a77fbb78f88)
https://youtu.be/1WnsC1SzJCg?si=lfCAlqz71AiTfo1g 3:41:30-3:51:00

**Comment by ShadowLotus232** [comment]
Central post covers issue #427
