### ISSUE TITLE
Out of range and Deserializations errors on battle start

### ISSUE THREAD

**Issue by Raw227** [stackcollision/Nebulous-BugReporting#575]
During the battle encounter phase, I received some OOR and Deserialization errors. 
[Raw game 12 log.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14725061/Raw.game.12.log.zip)
![Out of range and Deserializations on battle start](https://github.com/stackcollision/Nebulous-BugReporting/assets/163604224/a06918ce-3108-4098-9b4e-e1cc0d138fc5)
https://youtu.be/1WnsC1SzJCg?si=A9ra1hfp47jr6J5x&t=5400 1:30:00

**Comment by Dargaribdus** [comment]
[Game_12-_F-LzBmS5UKQFAbpSy41ZQrawpost.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14781478/Game_12-_F-LzBmS5UKQFAbpSy41ZQrawpost.zip)

Save for this report
