### ISSUE TITLE
Trajectory Planner is still wrong for inner moons

### ISSUE THREAD

**Issue by TexanByTrade** [stackcollision/Nebulous-BugReporting#579]
**Describe the bug**
The trajectory planner gives wrong results for midpoint velocity and total time when flying between the inner Jewel's Rest moons. At low accel times, the fleets move properly slow towards the target, and then they teleport to the destination when the false Total Time has elapsed. 

**To Reproduce**
1. Load save below.
2. Command TF Lithium to move to Garnet with the minimum burn time of 2 Hours 17 Minutes.
3. This flight _should_ take over 8 days, but the planner says it only takes over 2 days. 
4. Execute turn and watch TF Lithium fly. After 2 days 11 hours it teleports to Garnet.

**Additional context**
Previous fix was converting the calculation to use local coordinates. This bug is more devious, but I think it might lie in using an iterative solution. If the target location changes too much between iterations, it might fail to converge properly (perhaps this might happen any time the moon's orbital period is much lower than the total travel time expected). The iteration _ends_ on calculating the future position of the target one more time. If in the previous iteration the target was close by, it will result in a lower acceleration time, but then the final iteration might calculate the target far away again. And vice versa (there is a pic in Discord of an acceleration/travel time being _too long_ based on the distance given).

**Attachments**
[GP 4 Life-KVoa74nONUGJeq-mT4St0w.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14735629/GP.4.Life-KVoa74nONUGJeq-mT4St0w.zip)

**Comment by ShadowLotus232** [comment]
Possible connection to issue #368
