### ISSUE TITLE
ArgumentOutOfRangeException red text error

### ISSUE THREAD

**Issue by thebluehaloguy** [stackcollision/Nebulous-BugReporting#58]
**Describe the bug**
Here is some red text I got when I was shooting at the enemy fleet in a PD test
**To Reproduce**
1. Have a missile ship, in my case a destroyer with 4 VLS-2's and many missile systems.
2. Shoot enemy fleet, had a Corv, a frig, a destroyer and an axford. Missile PD, flak PD, laser PD and defenders.
3. Observe red text after it starts getting close to enemy

**Expected behavior**
It was expected I wouldnt get red text

**Additional context**
N/A

**Attachments**
![Screenshot (129)](https://user-images.githubusercontent.com/108600554/177479735-1521786d-f21d-43b4-8d44-ce0c6a8e35e0.png)

https://user-images.githubusercontent.com/108600554/177479953-d9036d44-06ad-4655-b301-0d04a57453f6.mp4

[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/9052130/Player.log)

**Comment by TexanByTrade** [comment]
Got it in multiplayer as well. I was host:
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/9052419/Player.log)

**Comment by thebluehaloguy** [comment]
DesertSaker already made this error post, he should update text name so people don't spam this error.
