### ISSUE TITLE
SAR intel is only created initially, not updated.

### ISSUE THREAD

**Issue by Snowblind111** [stackcollision/Nebulous-BugReporting#581]
**Describe the bug**
When a fleet is initially spotted, it has a Synthetic Aperture Radar image assigned for it on the strategic map. This image does not update when the fleet has ships split off, or has ships in it lost in combat. The image also does not update if the fleet is lost from radar and later reacquired - only the initial image is ever available.

**To Reproduce**
1. Examine an enemy fleet in conquest. Take note of the approximate number of ships in the fleet
2. Send a fleet to that fleet's POI and kill most of its ships off, leaving a few survivors so the fleet will still be there on the conquest screen
3. Examine the fleet again post match
4. The fleet's SAR will still show it having the old number of ships. If the almost destroyed fleet then moves elsewhere, its FLARE will show the correct number of ships.

**Expected behavior**
SAR should update with reasonable frequency, so fleets can't have dozens of ships cycled in and out without the intel changing from its initial appearance.

**Additional context**
I don't know whether this same bug affects FLARE.

**Comment by ShadowLotus232** [comment]
Central post also covers issue #522 

pretty sure this is just a symptom of placeholder systems for the beginning of intel, though
