### ISSUE TITLE
Month missing in the top center date display

### ISSUE THREAD

**Issue by LaffeyChanNya** [stackcollision/Nebulous-BugReporting#584]
**Describe the bug**
Some regional date formats use non latin characters. Game cannot display them, and will cause the current month to entirely or partially disappear from display.

**To Reproduce**
1. Change regional date format to one that uses non latin characters.
2. Open conquest match
3. No month :(

**Expected behavior**
See month :)

**Attachments**
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/163597764/30c95213-f59e-45f7-a475-7a69aa5f4a64)
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/163597764/269dbe55-f4e9-404b-b9e2-95ee2bbeb4fa)

**Comment by stackcollision** [comment]
Font atlas does not contain non-english glyphs.  Fix not planned.
