### ISSUE TITLE
Game 23 - Unplanned Exile - Team 2 relogged after 1st battle of turn 1 .... and now we're all spectators.

### ISSUE THREAD

**Issue by ignifluous** [stackcollision/Nebulous-BugReporting#589]
**Describe the bug**
After the first battle of turn 1, team 2 had the usual 'missing ships/POIs/tracks' error, and did the usual disconnect, rejoin pattern.

However , on rejoining, all three members of team 2 were shown the "choose a team" dialog.

Our names were shown in the T2 list as OFFLINE.

On attempting to join T2 again .... we appeared to join a phantom team 3, with our names showing as gray/white in the chat and *ALL* POIs showing as red/hostile (see screenshot below).

Host reloaded the save, we joined again, and T2 were now able to successfully reconnect. An attempt to reproduce the behaviour failed.

(I have no idea! We attempted to reproduce by reloading save, then unlogging/relogging T2, but did not reoccur.
1. Approach your nearest OSP agent
2. Apply for asylum

**Expected behavior**
T2 should have joined back into their teams as normal

**Additional context**
It was likely all team 2 members were out of server at the same time, but whether that had an impact or not, unknown.

**Attachments**
Attach any screenshots, logs, fleet files, etc that may help.
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/1892468/cd3a23dd-b847-4eda-9868-cc002957284e)

Full log from immediately after the error occurred, the rejoin is the last events in the log.
[EXILE log.txt](https://github.com/stackcollision/Nebulous-BugReporting/files/14797655/EXILE.log.txt)

**Comment by Phoenix51505** [comment]
We got exiled later as well, I think it happened mid turn execution. At the very bottom of the log attached you can see our login attempts and NRE's
[Exile.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14798377/Exile.log)
