### ISSUE TITLE
Disconnected from match

### ISSUE THREAD

**Issue by AMckernan11** [stackcollision/Nebulous-BugReporting#6]
**Describe the bug**
game had red text and we ended up disconnected
**To Reproduce**
Absolutely no idea
**Expected behavior**

**Additional context**
7 other people were disconnected including the host
**Attachments**
Attach any screenshots, logs, fleet files, etc that may help.
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/9033979/Player.log)

**Comment by Enderminion1** [comment]
Lots of S1 missiles and several S2 missiles were in flight at the same time

**Comment by Enderminion1** [comment]
Another Lo
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/9034013/Player.log)
g

**Comment by Enderminion1** [comment]
Another Log
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/9034036/Player.log)
