### ISSUE TITLE
Cargo Vessels unidentifiable on the TRACK ANALYSIS menu.

### ISSUE THREAD

**Issue by Dargaribdus** [stackcollision/Nebulous-BugReporting#602]
**Describe the bug**
Some cargo vessels cannot be identified in the TRACK ANALYSIS menu. This not only instantly flags them as Cargo Vessels for free for the player, but gives you the NO TARGET SELECTED error when a target is clearly selected. It's only cargo vessels that have this problem, but not all cargo vessels have this problem.

**To Reproduce**
Open the attached save file
Look at NR19, a cargo ship
Be unable to flag it. 

**Expected behavior**
All Cargo vessels should be identifiable, both to obfuscate them for the players and force them to engage with the intel mechanic, and to prevent UI inconsistencies. 

**Attachments**
Attach any screenshots, logs, fleet files, etc that may help.
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/163589943/04607c9a-1a54-4fb1-bf03-9fd48881e2e3)
[Darg Game 25 Turn 1 Battle 1 Post.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/14878809/Darg.Game.25.Turn.1.Battle.1.Post.zip)
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/163589943/56dcec55-1f7b-41cc-b894-af8ea128024d)

**Comment by stackcollision** [comment]
Was this save file from before the identification system was introduced, and were those cargo ships that can't be identified already in-flight before the patch?

**Comment by Dargaribdus** [comment]
No. This save was freshly made as of the day we played the game, same day the issue was posted and after the identification system was added.
