### ISSUE TITLE
Background scale indicate does not scale with thesame inertia that the camera zooms

### ISSUE THREAD

**Issue by Khanage-jmc** [stackcollision/Nebulous-BugReporting#620]
**Describe the bug**
When zooming in and out in the conquest strategic map, the background grid of red dots scales at a different rate than the rest of the map.

**To Reproduce**
1. Start a new conquest game.
2. Zoom out to the maximum map extents, observe the sparse grid of red dots for indicating scale.
3. Rapidly zoom in, observe the background grid becomes dense before the zoom level "catches up" to it.

**Expected behavior**
Scale grid should grow and zoom at the same rate as the map view

**Comment by stackcollision** [comment]
Intentional
