### ISSUE TITLE
NRE upon trying to Exit to Main Menu.

### ISSUE THREAD

**Issue by Spedicyulous** [stackcollision/Nebulous-BugReporting#623]
**Describe the bug**
Attempting to Exit to the main menu from within a conquest game fails to return to the main menu and throws an NRE.

**To Reproduce**
1. Start a game
2. Open up the Esc menu
3. Hit 'Exit'

**Additional context**
This bug is new to the most recent version. Load and Settings do not work either, but they don't throw an error. This bug is problematic as we frequently need to disconnect and rejoin to fix desync issues.

**Attachments**
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/14972480/Player.log)

**Comment by Highrs** [comment]
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/8764280/dc8de30d-caa1-4c6d-a630-c85339b15d80)
This happens in the game creation screen as well.
