### ISSUE TITLE
Double Clicking a TF or TG Does Not Zoom to Target

### ISSUE THREAD

**Issue by Dargaribdus** [stackcollision/Nebulous-BugReporting#639]
**Describe the bug**
Sometimes Double Clicking a TF or TG Does Not Zoom to Target and instead zooms the player out to the maximum level, which provides  too much information to be useful. Reliably happens on TF Eight and TG Nine

**To Reproduce**
1.Double click TF Eight or TG Nine
2. Giga zoom
3. Double click again
4. Proper zoom

**Expected behavior**
Zoom should go directly to the target location. 

**Additional context**
Both of these fleets were created manually.

**Attachments**
Attach any screenshots, logs, fleet files, etc that may help.
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/163589943/46a8910f-dd45-4e11-8251-d0f752ff057b)
[Game 26-BI2zJHMw2EW_S5DQbZq6GA.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/15123198/Game.26-BI2zJHMw2EW_S5DQbZq6GA.zip)

**Comment by Phoenix51505** [comment]
The first double click sends the camera to max zoom, then trying it again zooms in correctly.
