### ISSUE TITLE
Sarissas hitting parent destroyer hull when aiming at approx 0 degrees elevation along hull

### ISSUE THREAD

**Issue by Snowblind111** [stackcollision/Nebulous-BugReporting#64]
**Describe the bug**
When engaging targets that lie roughly towards the destroyer's direct front or rear, no projectiles can be seen heading towards the target missiles, and no missiles are destroyed. Given that the behavior is markedly worse on the destroyer's C3 mounts (which have a wider hull profile than the side C2s), and that the projectiles do not fail to emerge when engaging targets to the side where the hull has far less overhang, the Sarissa projectiles are presumably impacting their firing ship's hull immediately upon being fired. 

**To Reproduce**
1. Load a destroyer covered into Sarissas into the shooting range
2. Waypoint a salvo of missiles directly in front of where the spinal is aiming, and then waypoint them directly towards the destroyer
3. Watch some or all of the guns fail to shoot projectiles at their targets repeatedly, with some potential variation depending on if you got the angle exactly right.

**Expected behavior**
Sarissa acquire missile, Sarissa shoot tungsten at missile, missile explode hopefully.

**Additional context**
Given that the destroyer's C2 and C3 mounts aren't exactly unusual, this is likely to be a problem across many mounts on many hulls.

**Comment by sdk2013** [comment]
Successfully replicated issue on Keystone dorsal C3.

Tested other ships that seemed like they might have issues:
Unable to replicate with FFL c3 mount
Replicated with CL mount 1 firing fore
Replicated with CL mount 5 firing backward
Replicated with CH mount 4 firing at fore & ~5 degrees starboard, no altitude.
Replicated with CH mount 5 firing aft

General pattern: Sarissas seem to struggle with long, flat surfaces and have a tendency to catch the edge of them.

**Comment by Snowblind111** [comment]
The FF's C2s do it as well, and very occasionally the FF's C3s when shooting at around the absolute limit of the Sarissa's depression.
