### ISSUE TITLE
Ships fail to spawn correctly at Conq start.

### ISSUE THREAD

**Issue by Apocal43** [stackcollision/Nebulous-BugReporting#669]
**Describe the bug**
The previous bug involving the ships improperly spawned at the start of a Conquest match has re-appeared.  At match start, many ships will be assigned as Independent and fail to spawn anywhere on the map.

**To Reproduce**
1. Great Powers, 300k.
2. Load massive navy with plenty of flagships.
3. Start game.
4. Inconsistently happens with Great Powers.

**Additional context**
Previously reported:
https://github.com/stackcollision/Nebulous-BugReporting/issues/504
https://github.com/stackcollision/Nebulous-BugReporting/issues/432
 
**Attachments**
[New Conquest Game-glldZzcHeUqLtPsoG8VC0w SHIP SPAWN.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/15235593/New.Conquest.Game-glldZzcHeUqLtPsoG8VC0w.SHIP.SPAWN.zip)

**Comment by stackcollision** [comment]
Updated initial placement algorithm, report invalid
