### ISSUE TITLE
Last missile per VLS per missile type gets eaten by void fairies

### ISSUE THREAD

**Issue by Snowblind111** [stackcollision/Nebulous-BugReporting#67]
**Describe the bug**
The last missile of each kind in each tube is expended without launching when the ship is ordered to fire them e.g. if four Pilums and 2 Atlatls in a single VLS are ordered to fire, only 3 Pilums and 1 Atlatl will emerge from the launching ship, and dumping two VLS with the same loadout will launch 6 Pilums and 2 Atlatls instead of the expected 8 Pilums + 4 Atlatls.

**To Reproduce**
Queue up a missile volley that expends the last missile of a particular kind in a particular VLS
Wait till missiles are launched
The salvo will contain one less missile than it should - the last missile simply won't be fired and the ammo count will be reduced to zero with no missile fired.

**Expected behavior**
The last missile should fire when it is fired.

**Comment by sdk2013** [comment]
I have replicated this bug as described using my own fleets.
