### ISSUE TITLE
NRE in ship builder

### ISSUE THREAD

**Issue by d-petersen** [stackcollision/Nebulous-BugReporting#671]
**Describe the bug**
I built a Nakano class lander and then noticed there was a NRE at the bottom of the screen after playing around with it for a little bit in the fleet editor. I didn't notice exactly when the log appeared, so I'm unsure how to reproduce it.

Though I doubt it's relevant to the issue, I've also included the blueprint for the ship.

**Attachments**
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/15289328/Player.log)
[Troopship.zip](https://github.com/stackcollision/Nebulous-BugReporting/files/15289336/Troopship.zip)

**Comment by stackcollision** [comment]
These are related to the Halo mod.  Do not have mods loaded during testing.
