### ISSUE TITLE
Cease Fire does not prevent missiles from firing once programming has started

### ISSUE THREAD

**Issue by Khanage-jmc** [stackcollision/Nebulous-BugReporting#68]
**Describe the bug**
The Cease Fire order does not prevent missiles already being programmed from firing. It does prevent additional missiles from being programmed if they were queued.

**To Reproduce**
1. Fire more missiles than the ship has missile programming slots
2. Click "CF" order
3. Missiles already being programmed will still fire.

**Expected behavior**
CF order should prevent missiles from firing.

**Comment by DesertSaker** [comment]
manually cancelling the shoot order also does not prevent missiles in the process of programming from being launched.
