### ISSUE TITLE
Missile templates and colorblindness settings

### ISSUE THREAD

**Issue by CrowX8** [stackcollision/Nebulous-BugReporting#698]
Description of the bug: 30 legs, sharp fangs, spins webs... emits gas? 

in game setup screen: navy design I loaded ships with missiles and another friendly player loaded a ship with missiles 
my missiles appeared with blue text on targeting mode and primary seeker. I used deuteranopia
the other missiles appeared with green text on the targeting mode and the primary seeker. they used default.

I suspect that the color blindness settings of the player are being saved to the missile temple or  the player is sending the color data to the server rather than all missiles displaying the colors of the viewing player.

I would expect that all of the colors to appear per my settings.

reconnected to the game, missiles still appear same as above.
disconnected, changed my colorblindness setting to default and reconnected, missiles appeared the same as above.
removed my ship templates and re-added with default setting, appears same.

Green is the color for hostiles using my settings.

Visual below
![friend's missile](https://github.com/stackcollision/Nebulous-BugReporting/assets/163678403/7433a2fb-94e2-4d9f-b071-64361c5d8057)
![my missile](https://github.com/stackcollision/Nebulous-BugReporting/assets/163678403/6a120313-8e4e-46a9-b695-d74c4bed6b17)
![both missiles](https://github.com/stackcollision/Nebulous-BugReporting/assets/163678403/2209bf0f-b949-4118-994b-95ce651f1f81)

**Comment by achilleasang** [comment]
Just to clarify, I was the other player, I use no colourblind settings and it's also like this on my end
