### ISSUE TITLE
Ship Given Launch Order Launches Too Many Missiles

### ISSUE THREAD

**Issue by sdk2013** [stackcollision/Nebulous-BugReporting#70]
**Describe the bug**
Title- When given a launch order, ship launches too many missiles. 

**To Reproduce**
1. Load fleet into skirmish
2. Launch single wake val at enemy
3. Two Missiles Launch

**Expected behavior**
Single missile launches

**Additional context**
If multiple VLS pods are available, missiles will be split between pods. 

**Attachments**
Video of bug: https://youtu.be/q4i5xybm49Q
[Fleet File](https://github.com/stackcollision/Nebulous-BugReporting/files/9077456/0fleet.zip)

**Comment by sdk2013** [comment]
A Note here- this seems to act correctly if you cancel one missile before firing.

Not sure if this is still a bug or just UI weirdness or just me being dumb.

**Comment by stackcollision** [comment]
Not a bug, this is the way the missile UI works.  The selection of the missile queues up one shot, and clicking again fires the second.
