### ISSUE TITLE
Game 34 - Nonexistent TGs showing up in TACSIT

### ISSUE THREAD

**Issue by ShadowLotus232** [stackcollision/Nebulous-BugReporting#712]
**Describe the bug**
Several Task Groups that do not exist on anyone else's machine showed up in my TACSIT after loading into the game for the first time.

**To Reproduce**
1. Be a client
2. Load into the game
3. See ghost groups

**Expected behavior**
All TACSIT items to line up with all other players.

**Additional context**
The actual TF/TG count was 11/0, my TACSIT showed 3/9
The TGs that didn't exist had zero ships and invalid orders

**Attachments**
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/34362934/f3cf576f-3f2f-463a-ac3f-a8ba4e1c44c2)

Full log: (NREs did not occur in conjunction with the TACSIT error, though the last one did happen afterwards when exiting the game to re-log)
[Game 34 - Incorrect TACSIT.log](https://github.com/user-attachments/files/15687639/Game.34.-.Incorrect.TACSIT.log)

**Comment by HunteRNeB** [comment]
![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/159951258/188806a8-2ff2-4716-bdbf-62a74ec1e62f)

gaming
