### ISSUE TITLE
Seeker cones displaying incorrectly on testing range

### ISSUE THREAD

**Issue by ignifluous** [stackcollision/Nebulous-BugReporting#719]
**Describe the bug**
When firing S2H from this fleet on the test range, the seeker cones are not displayed correctly.

![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/1892468/95871a99-b41f-418c-8023-ff9d3352d21e)

![image](https://github.com/stackcollision/Nebulous-BugReporting/assets/1892468/1bcebc6d-4043-4e30-a515-7e9bde4dade9)

**To Reproduce**
1. Load the attached fleet
2. Start test range, select a target fleet
3. Queue a missile launch
4. Observe seeker cone display during flight

**Expected behavior**
The seeker cone should show display as on the public branch - it should show its sides, not just the terminal plane, as well as the target indicator.

**Attachments**
[sample fleet.zip](https://github.com/user-attachments/files/15751622/sample.fleet.zip)

**Comment by smolcake** [comment]
Slight update from the Thursday multiplayer, this issue occurs in multiplayer too. Image attached for reference sorry about opsec ;P


<img width="345" alt="wrongcone" src="https://github.com/stackcollision/Nebulous-BugReporting/assets/163495564/7fe45807-093b-4f6a-b9be-789373926bbe">
