### ISSUE TITLE
EO seekers fired on waypoint paths are going after decoys and missiles. 

### ISSUE THREAD

**Issue by ZachoWacko** [stackcollision/Nebulous-BugReporting#73]
**Describe the bug**
Launching EO without a target, as in a validator for a cruise missile attack makes the missile go after decoys instead of discriminating as in the description.  

**To Reproduce**
1. Load a ship with an S3H missile with a radar and EO validator. Or just EO seeker
2. Shoot on a waypoint path
3. Missiles will go after decoys as a validator. 
4. Seeker by itself will go after decoys and hostile missiles. 

**Expected behavior**
Per the description, it should not go after decoys, and it should have a size gate as radar to stop missile seeking with ASMs.
 
![image](https://user-images.githubusercontent.com/48743874/178151790-1f894332-0aa8-4e5d-9fdd-86d2c07b11ed.png)

**Comment by Cebasiz** [comment]
This also happens when fired on direct attack missions. Mazer noticed that the active decoys have an EO sig so that's likely what's causing it.
