### ISSUE TITLE
PF-440 fire 20 mm at large ships

### ISSUE THREAD

**Issue by iamgoldstei** [stackcollision/Nebulous-BugReporting#743]
**Describe the bug**
Observe that interceptors will fire 20 mm cannons at larger ships even though this can't damage them

**To Reproduce**
1. Equip CVE with PF-440 with 20 mm, and both HE and HE Frag S1
2. Load testing range
3. Launch PF-440
4. Perform attack order on larger ship (e.g. FF, CL)
5. Observe that 20 mm is used in the attack

**Expected behavior**
Weapons that cannot harm a target ship will not be used.

[Player-prev.log](https://github.com/user-attachments/files/16669351/Player-prev.log)

**Comment by iamgoldstei** [comment]
[CV Test.zip](https://github.com/user-attachments/files/16669417/CV.Test.zip)

**Comment by stackcollision** [comment]
Craft do not filter weapon type by target yet.  For now you will have to babysit which weapons are active.
