### ISSUE TITLE
OSP Scout Flying inside target. 

### ISSUE THREAD

**Issue by ZachoWacko** [stackcollision/Nebulous-BugReporting#751]
Tell Scout to attack a target. 
![20240820015338_1](https://github.com/user-attachments/assets/2356cf72-4a1f-4585-bbc8-0da7fd50e4e9)

**Comment by ZachoWacko** [comment]
Too add, Scout had Jammers loaded.

**Comment by Enderminion1** [comment]
Have observed with Jammer equipped AN Interceptors targeting a container liner, same reproduction steps
