### ISSUE TITLE
Enemy craft tracks display FLIGHT #

### ISSUE THREAD

**Issue by RyMarq** [stackcollision/Nebulous-BugReporting#756]
**Describe the bug**
[FLIGHT #] is displayed before track name on enemy Craft.

**To Reproduce**
See tracks (with enough intel, it seems) on Craft, the information includes [FLIGHT #] at start

**Comment by titowulk** [comment]
I reproduced this on friendly craft as well, I think it happens if you attempt to launch more then one flight at a time
