### ISSUE TITLE
Craft Instantly Deploying When Launch Order Given, Teleporting Through Hangar Doors.

### ISSUE THREAD

**Issue by GoodNut** [stackcollision/Nebulous-BugReporting#762]
**Describe the bug**
Craft Instantly Deploying When Launch Order Given, Teleporting Through Hangar Doors.

**To Reproduce**
Launch a craft, in this case it was a Claymore.
Once armed, it will instantly appear on the deck of the CVE, and fly away while the hangar door animation plays.

**Expected behavior**
Craft should be riding the hangar elevator up.

**Additional context**
Testing range, same session as my previously mentioned testing range crash.

**Attachments**
Attached
[8-20-2024 Good Nut - Testing Range Crash Log.txt](https://github.com/user-attachments/files/16679199/8-20-2024.Good.Nut.-.Testing.Range.Crash.Log.txt)

**Comment by stackcollision** [comment]
Can't reproduce.  Need a video and reliable repro steps.
