### ISSUE TITLE
Command S2H missiles sometimes launch 2nd stage right away

### ISSUE THREAD

**Issue by captainwolfer** [stackcollision/Nebulous-BugReporting#77]
I had a frigate fleet with a bunch of S2 and 4 CMD S2H missiles, and I noticed that of 4 S2H missiles launched, all 4 activated their second stage almost as soon as they launched, and the second stage ran out of fuel multiple KM from the targets. I then went into small test range with a frigate with only S2H missiles against some target ships, and in 5 tests (seperate matches) where 1 salvo of 5 CMD S2H missiles were launched, 1 test had 2 missiles launch 2nd stage right away, and 1 test had 1 missile launch 2nd stage right away. In the other 3 tests all S2H missiles preformed correctly.

**To Reproduce**
1. Load small test range, using the fleet file attached as your fleet and any fleet as a target
2. Fire 1 salvo of S2H missiles. Either jam the hostile fleet or pause AI to keep them from shooting the frigate
3. Watch to see if some of the missiles activate 2nd stage basically as soon as their engines turn on
4. If error does not occur, end match and repeat steps 1-4.
5. It may take several tries, as the bug only occurred in 2 of 5 tests done, and I could not figure out if there was a more reliable way to cause it

**Expected behavior**
Missile should not stage as soon as they launch, and normally they don't

**Attachments**
Proof screenshots and fleet file I used to fire the missiles in my tests
![20220720141756_1](https://user-images.githubusercontent.com/108598089/180085274-ffd069c9-7e46-4112-a34c-ec6b8211d75c.jpg)
![20220720142043_1](https://user-images.githubusercontent.com/108598089/180085275-38138349-515f-4e0a-a9c4-b66049bbfcd9.jpg)

[1S - CMD S2H Bug.txt](https://github.com/stackcollision/Nebulous-BugReporting/files/9154626/1S.-.CMD.S2H.Bug.txt)

**Comment by Snowblind111** [comment]
I just had a really weird moment during a test where every single one of 24 simultaneously launched Cyclones displayed this bug at once. Reloading a save just before it happened and repeating the same user input to replicate conditions couldn't reproduce the bug, sadly.
