### ISSUE TITLE
Craft failed to dock and went to the void.

### ISSUE THREAD

**Issue by thebluehaloguy** [stackcollision/Nebulous-BugReporting#779]
**Describe the bug**
Scout group of 3 tried to dock a mini monitor carrier, two landed just fine while the last scout just drifted off.

**To Reproduce**
Cant reproduce so far, sorry boss.

**Expected behavior**
It was expected all craft were to dock normally

**Additional context**
Some additional context, the scouts just killed some bombers with some 20mm right before docking

**Attachments**
https://www.youtube.com/watch?v=usVE06pEIow

**Comment by ZachoWacko** [comment]
Too add got the log for it. 
[Player.log](https://github.com/user-attachments/files/16734538/Player.log)

**Comment by thebluehaloguy** [comment]
Zacho so kind!
