### ISSUE TITLE
Disconnected in 4v4 when my BB had 3 different players spam missiles at it

### ISSUE THREAD

**Issue by captainwolfer** [stackcollision/Nebulous-BugReporting#9]
**Describe the bug**
I got disconnected in a 4v4 while I was trying to deal with 3 different players having spammed missiles at me. There was a lot of S1 missiles fired by Goldstei, S2 missile fired by Tempest Fox3, and what were probably either S2 or S3 2 stage missiles fired by a third player. In addition, my battleship was firing S1 active radar defensive missiles (it started with like 140 missiles), and had 4 defender turrets.

**Attachments**
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/9033976/Player.log)

**Comment by Tempestfox3** [comment]
Was in the same game and was disconnected slightly prior to everyone else. Right after firing my missiles log file added
[Player.log](https://github.com/stackcollision/Nebulous-BugReporting/files/9033993/Player.log)
