### ISSUE TITLE
Intel Incorrectly Analyzing Target Condition

### ISSUE THREAD

**Issue by DesertSaker** [stackcollision/Nebulous-BugReporting#90]
**Describe the bug**
Intel will regularly report a heavily damaged target at 100% condition, or a barely touched target at nearly 0% condition.
This is used with an intelligence center and two annexes. 

**To Reproduce** - not consistently reproducable
1. Use a fleet with intel centers and annexes
2. hit a ship with a missile
3. See error

**Expected behavior**
If given enough time, intel should display target condition correctly, or at least with closer values

**Additional context**

**Attachments**
Attach any screenshots, logs, fleet files, etc that may help.
![Nebulous Screenshot 2022 07 30 - 22 38 56 25](https://user-images.githubusercontent.com/108598484/182010896-cffe6ead-6b63-4f13-aa0d-53f93d270914.png)

**Comment by rmorrise** [comment]
Is the damage within the error range for intelligence?
https://www.youtube.com/watch?v=7m976g6byys&t=7s

**Comment by stackcollision** [comment]
Intel has a percentage of error in its assessment, and it also only updated periodically.
