### ISSUE TITLE
Number of Queued Missiles Increase on Launch Click With Non-Zero Missiles Selected

### ISSUE THREAD

**Issue by NicholasZonenberg** [stackcollision/Nebulous-BugReporting#93]
**Describe the bug**
Recent patch notes have said that when you click to launch missiles it will no longer add an additional missile to the number of missiles launched as long as the number of missiles queued are non zero.

When I go into skirmish to test missiles and use 'alt+click' to queue up missiles and then 'click' to launch the missiles another missile is added to the launch beyond the amount queued via 'alt+click'

**To Reproduce**
1. Go into Skirmish
2. Use 'alt+click' to cue up missiles
3. Use 'click' to launch missiles
4. The number of missiles launched is the amount you queued via 'alt+click' + 1.

**Expected behavior**
After cueing up a non zero amount of missiles to launch clicking to launch the volley should only fire amount queued instead of adding + 1 from the launch click

**Additional context**

**Attachments**
Video of it in action: ( unlisted on my youtube channel.  Let me know if I should change that ) https://youtu.be/VF7WN1wv0g8

**Comment by stackcollision** [comment]
The stated changes only apply to the Track widget.  Position widget is unchanged.
